### ISSUE TITLE
ActionScheduler_DataController::free_memory() sets a private property on $wp_object_cache?

### ISSUE THREAD

**Issue by thomascharbit** [Prospress/action-scheduler#1008]
Hi,

I got some errors on a WooCommerce website when AS is trying to free up some memory.

I don't understand how this part of the function is supposed to work:

```php
		/**
		 * @var $wpdb            \wpdb
		 * @var $wp_object_cache \WP_Object_Cache
		 */
		global $wpdb, $wp_object_cache;

		$wpdb->queries = array();

		if ( ! is_a( $wp_object_cache, 'WP_Object_Cache' ) ) {
			return;
		}

		$wp_object_cache->group_ops      = array();
		$wp_object_cache->stats          = array();
		$wp_object_cache->memcache_debug = array();
		$wp_object_cache->cache          = array();

		if ( is_callable( array( $wp_object_cache, '__remoteset' ) ) ) {
			call_user_func( array( $wp_object_cache, '__remoteset' ) ); // important
		}
```

Because the cache property in $wp_object_cache [is a private property](https://github.com/WordPress/wordpress-develop/blob/6.3/src/wp-includes/class-wp-object-cache.php#L33)

So executing ` $wp_object_cache->cache = array();` results in a PHP fatal error.

Am I missing something?

I am using PHP 7.4.

Thanks!

**Comment by barryhughes** [comment]
Hi @thomascharbit,

I'm a little unsure if this is the very best way for us to free memory (though perhaps there weren't many other alternatives), but I'm also surprised that you are experiencing a fatal error—because private fields like the one you mentioned are accessed via a [magic getter](https://github.com/WordPress/wordpress-develop/blob/6.3/src/wp-includes/class-wp-object-cache.php#L85-L95).

Are you using an external object caching implementation/can you replicate this error on a brand new WP site, running just Action Scheduler (no other plugins, mu-plugins or drop-ins)? Can you share a backtrace?

**Comment by thomascharbit** [comment]
Hi, thanks for your feedback.
Yes I am using the Docket Cache object cache and it looks like they are not implementing this magic getter.
So I will open an issue there, sorry!

**Comment by barryhughes** [comment]
No problem. If there's any further feedback for us—Docket Cache devs, please don't hesitate to chime in here directly—then leave some comments and we can re-open if needed.

*(I'm partly thinking that a possible interpretation of the [current WP Object Cache implementation](https://github.com/WordPress/wordpress-develop/blob/6.3/src/wp-includes/class-wp-object-cache.php#L85-L95) is that reading/writing to those fields is allowed, but perhaps discouraged.)*
