### ISSUE TITLE
Batch size remains 1

### ISSUE THREAD

**Issue by superjunky** [Prospress/action-scheduler#1009]
I have used the supplied filters to increase processing speed, but on both my dev and production servers they keep processing 1 task at a time. 1 every minute as per the cron calls.

I have been struggling with this for a while, there must be something I'm overlooking, although I read all documentation multiple times.

I gave wp-cli a go, but it gave me the same result.

Can someone please help me out?

**Comment by barryhughes** [comment]
Hi @superjunky—to confirm, you've already looked at the following guidance?

- [Increasing batch size](https://actionscheduler.org/perf/#increasing-batch-size) *(how many actions can be processed in a single batch).*
- [Increasing concurrent batches](https://actionscheduler.org/perf/#increasing-concurrent-batches) *(how many batches are allowed to run simultaneously).*

> I gave wp-cli a go, but it gave me the same result.

It would be awesome to get a little more detail about how you tested this—for instance, if you already configured things via the filters linked to above, what did you set them to, and how did you test things with WP CLI? 

It could also be useful to know how many overdue actions were waiting since, if there were only 10 actions that needed to be processed at the time you started the queue, they'd presumably all have been claimed as part of the same batch (...in other words, even if the configuration *allows* for concurrent processing, this won't be utilized unless the number of waiting tasks requires it).

**Comment by barryhughes** [comment]
Closing (no follow-up).
