### ISSUE TITLE
Default orderby in ActionScheduler_wpPostStore.php prevents index usage leading to long execution times

### ISSUE THREAD

**Issue by negrusti** [Prospress/action-scheduler#101]
```
explain SELECT p.ID FROM wp_posts p WHERE post_type='scheduled-action' AND p.post_status='publish' AND p.post_modified_gmt <= '2017-10-23 03:42:01' ORDER BY p.post_date_gmt ASC LIMIT 0, 20;
+------+-------------+-------+-------+------------------------------------------------+---------------+---------+------+------+-------------+
| id   | select_type | table | type  | possible_keys                                  | key           | key_len | ref  | rows | Extra       |
+------+-------------+-------+-------+------------------------------------------------+---------------+---------+------+------+-------------+
|    1 | SIMPLE      | p     | index | type_status,type_status_date,post_modified_gmt | post_date_gmt | 8       | NULL |   78 | Using where |
+------+-------------+-------+-------+------------------------------------------------+---------------+---------+------+------+-------------+
1 row in set (0.00 sec)

mysql> SELECT p.ID FROM wp_posts p WHERE post_type='scheduled-action' AND p.post_status='publish' AND p.post_modified_gmt <= '2017-10-23 03:42:01' ORDER BY p.post_date_gmt ASC LIMIT 0, 20;
Empty set (3.09 sec)

```

**Comment by negrusti** [comment]
I think ORDER BY is not needed for delete or reset timeout operations

**Comment by negrusti** [comment]
perhaps specifying orderby = 'modified' in 
ActionScheduler_QueueCleaner.php
will be sufficient

**Comment by thenbrent** [comment]
Thanks for the report @negrusti.

> perhaps specifying orderby = 'modified' in
> ActionScheduler_QueueCleaner.php
> will be sufficient

Were you able to confirm that improves performance? If so, we can make that change.

In most cases, ordering by modified dates will clear the timeouts in the same order as ordering by post date, but in those cases where it doesn't, it probably yields a better result anyway. It makes sense to clear the actions which have been stuck (i.e. `modified`) the longest rather than those actions which were created earliest.

Also if you haven't already seen it, we're in the process of testing custom tables for Action Scheduler as we've found there are unavoidable perf issues with using custom post types for action data storage. You can find the pre-beta code for custom tables here: http://github.com/Prospress/action-scheduler-custom-tables/

**Comment by negrusti** [comment]
Since I've posted the issue, I've been able to resolve that without code modifications by adding a key on
(post_type,post_status,post_modified_gmt), need some time to test. Thanks!

**Comment by thenbrent** [comment]
> We are planning to use custom tables as soon as they will reach stable release

@negrusti that's great to hear. Please send an email to support@prospress.com as we'd love to work more closely with you during the beta testing phase. 🙂
