### ISSUE TITLE
Modify existing action

### ISSUE THREAD

**Issue by buggles333** [Prospress/action-scheduler#102]
I am using the WooCommerce Subscriptions plugin which uses your action-scheduler code.  I am trying to edit an existing action to change it's date.

The action looks like this in the database...

O:30:"ActionScheduler_SimpleSchedule":1:{s:41:"ActionScheduler_SimpleScheduletimestamp";s:10:"1544118885";}

How can I modify the timestamp?

**Comment by thenbrent** [comment]
> I am trying to edit an existing action to change it's date.

If you want to change a subscription's date, you should change the subscription's date not the scheduled action. Use `WC_Subscription::update_dates()`.

To modify an action, you'd unschedule and reschedule it. You can see an example of this being done by Subscriptions in `WCS_Action_Scheduler::update_date()` (which will run when a subscription's dates are updated and saved).

**Comment by noplanman** [comment]
@buggles333 @thenbrent

Hope it's ok to write here, even though this issue is well aged 🍷 

I'm faced with this exact "issue" and it would be awesome if there were a possibility to simply update the time of existing actions, without having to cancel and reschedule, which basically duplicates actions in the database.

Is there a pretty internal way of doing this, or would I have to do it manually with DB queries?
What is the reason that this is not a built-in feature? Are the actions supposed to be immutable?
