### ISSUE TITLE
“Scheduled Actions” does not execute Orders successfully.

### ISSUE THREAD

**Issue by jtruta** [Prospress/action-scheduler#1062]
Hi I would like some help with a problem occurring in my Woocommerce. I have an integration between Woocommerce and a ERP (bling.com.br).

- In the WordPress Panel under “**Woocommerce > Settings > Advanced > Webhooks**” I have 4 webhooks created, being:

1) **Webhook – Order Created (ID11)** – Used to create an order
2) **Webhook – Updated Order (ID12)** – Used to update an order
3) **Webhook – Created Product (ID7)** – Used to create a product
4) **Webhook – Updated Product (ID8)** – Used to update a product

- **The expected actions are:**

1) Webhook – Order Created (ID11) – When a customer creates an order in Woocommerce, it must be created in the ERP automatically;
2) Webhook – Updated Order (ID12) – When the order status is updated, it must be updated in the ERP automatically;
3) Webhook – Created Product (ID7) – When a product is created in Woocommerce, it must be created in the ERP automatically;
4) Webhook – Updated Product (ID8) – When you update product stock, it must be created in the ERP automatically;

I followed the procedure (https://github.com/woocommerce/action-scheduler/issues/847#issuecomment-1724718881) and added the line of code below in the “**functions.php**” of my child theme:

`add_filter( 'action_scheduler_queue_runner_concurrent_batches', function () { return 2; } );`

This code above solved the problem below that occurred for all Orders generated in my Woocommerce:

`“Maximum simultaneous batches already in progress (1 queue). No action will be processed until the current batches are completed"`

I did more tests and noticed the following behavior:

Orders are executed successfully only when there is a previous order (woocommerce_deliver_webhook_async) being executed with the status “**In Process**” When I place an order and there are no previous orders with the status “**In Process**” in “**Scheduled Actions**“, the order is classified as “**Unsuccessful**” after a while.
In the image below, I placed “**order 6334**” which had the status “**in process**” because it was the first order. After a while this “**order 6334**” will have the status “**Unsuccessful**“:

![22 05 24-pedido-6334-inprocess-1](https://github.com/woocommerce/action-scheduler/assets/170672821/f43148b6-b6ad-412b-baa9-8f7715a0cb8d)

But during this period as long as the status of “**Order 6334**” remains “**in process**“, all new orders will be processed successfully. See the image below for “**Order 6335**“, which **was executed successfully and very quickly by “Scheduled Actions“, because there is an “Order 6334” with the status “In Process“**:

![22 05 24-pedido-6335-done-1](https://github.com/woocommerce/action-scheduler/assets/170672821/e0d45018-f18a-41e1-8252-570511174d7f)

“**Order 6335**” was executed successfully and quickly, and had the status "**done**" 🙂 , but “**order 6334**“ had the status “**unsuccessful**” 🙁 :

![22 05 24-pedido-6334-unsuccessful-1](https://github.com/woocommerce/action-scheduler/assets/170672821/b292fa6a-6d64-4ff4-a552-d1ea8f6804d1)

It’s as if “**Scheduled Actions**” **was sleeping**. Upon receiving the first order, “**Scheduled Actions**” wakes up, but is unable to execute it, leaving this order in the “**In process**” state. During this period when an order is in the “**In Process**” status, it is as if “**Scheduled Actions**” was awake and ready to process all subsequent orders that arrive, executing these new orders quickly and successfully.

I'm using the following versions:
WordPress: 6.5.3
Woocommerce: 8.8.3
PHP: 8.0.30

How do I keep “Scheduled Actions” always awake, to execute all Orders?

Thanks for your help.

**Comment by jorgeatorres** [comment]
Hi @jtruta!

Thanks for reaching out, and I'm sorry that you're having trouble with Action Scheduler. In order to better assist you, and based on the information you've provided, we'd like to ask a few follow up questions:

- You mentioned a prior error that you were able to address by using the `action_scheduler_queue_runner_concurrent_batches` filter. The error message you posted is one that was changed in Action Scheduler years ago, and so we're wondering if you are actually running an up-to-date version of Action Scheduler. In some circumstances, a conflict with other plugins bundling Action Scheduler (other than WooCommerce) might result in an old version being used instead of the correct one. Have you tried to reproduce the problem with just WooCommerce active? Can you confirm what you see next to "Action Scheduler package" on the WooCommerce > Status screen?
- Also, we can see from the screenshot you've shared, that the actions were marked as failed after a timeout. Have you checked your server logs to see if something in particular is failing? For example, could it be that the URL the webhook is trying to contact is slow to respond or has some traffic-related protections? Note that the timeout can be increased to a different value by using the `action_scheduler_failure_period` filter, but we'd like to know more before suggesting a specific approach.

Looking forward to hearing back from you. Thanks!

**Comment by jtruta** [comment]
Hi @jorgeatorres 

Just to update you, I'm running some tests. I followed your guidance by deactivating the plugins and leaving only Woocommerce and 3 others that integrate with payment systems. I believe I have identified the plugin that causes the error [Smart Product Viewer](https://topdevs.net/smart-product-viewer/)

I will do more tests and confirm the results.

Thanks for your help.

**Comment by barryhughes** [comment]
Hi @jtruta, just checking in. Did you determine that the problem came from that plugin, or are you still facing difficulties?

**Comment by barryhughes** [comment]
Hopefully this is now solved, but please open a fresh issue if you still believe there is a problem within Action Scheduler itself.
