### ISSUE TITLE
Reasons for past-due actions

### ISSUE THREAD

**Issue by Dani2449** [Prospress/action-scheduler#1064]
![image](https://github.com/woocommerce/action-scheduler/assets/122624042/ae60c21c-d49a-46ad-8d4c-ee2418f6938b)

i got everytime this error

**Comment by barryhughes** [comment]
@Dani2449 to confirm, the problem here is that issues generally become **past-due**, within your site, or is it a specific problem with the `action_scheduler/migration_hook` task?

**Comment by Dani2449** [comment]
![image](https://github.com/woocommerce/action-scheduler/assets/122624042/f2b56771-4c16-41ca-9605-131970676f4f)

Hello @barryhughes it's just showing like this I am not sure if there is a problem caused to anything else just dont know why its going it.

I am using the plugin Popup Maker and WPForm and i think it start from there

**Comment by barryhughes** [comment]
Hi @Dani2449,

So it sounds like the queue isn't always running successfully. There are actually several different contexts in which Action Scheduler typically runs:

| Context                    | Supported 'out of the box'  | Requires web traffic  |
| ---------------------------|-----------------------------|-----------------------|
| WP Cron (async HTTP)       | **Yes**                     | **Yes**               |
| WP Cron (via system cron)  | No                          | No                    |
| Async HTTP                 | **Yes**                     | **Yes**               |
| WP CLI (via system cron)   | No                          | No                    |

As you can see from the above table, both of the default *('out of the box')* methods require your website to receive a regular flow of traffic, otherwise the queue runner may not be started. You can mitigate this by using a system scheduler ('cron') and, if you set this up for WordPress, then Action Scheduler should also be able to take advantage of it:

[developer.wordpress.org/plugins/cron/hooking-wp-cron-into-the-system-task-scheduler](https://developer.wordpress.org/plugins/cron/hooking-wp-cron-into-the-system-task-scheduler/)

If you haven't already done so, can you follow the steps outlined in the above post and see if that helps?

It's not clear if this is the problem, so it may be something else is happening (such as a 'rogue plugin' throwing an error or prematurely ending execution in a way that stops Action Scheduler for being able to reliably process the queue of waiting actions), but that is relatively rare so I'd recommend starting with the above. 

Note also that many web hosts have their own set of instructions for reliably invoking WP Cron, so you may also wish to search their help pages for further guidance.

**Comment by Dani2449** [comment]
i am for now using the Local to have the wrodpress on my computer first this is why i want to fix it.

i did so before but there were not problem it looks like after Popup Marker because i have some buttons on te website for call to action and i wanted when you click it will use the WPForm if you can suggest how to do it easyer or with other plugin i think it will work.

can you suggest a better plugin to see if this problem is repyting.

**Comment by barryhughes** [comment]
If the problem started after you activated Popup Marker, I guess the next thing to test is if it is solved when you deactivate it. Then, you would have a pretty good idea if that is truly the source of the problem.

Additionally, you could:

- Look at any error logs being generated, and try to pick out those that relate to Popup Marker or Action Scheduler.
- Get in touch with the author of (or support team for) Popup Marker, and see if they can help.

Again, that's only if you believe it is the source of the problem. I'm afraid I am unfamiliar with Popup Marker and do not have any recommendations for replacements.

**Comment by Dani2449** [comment]
it's strange it still repeating it i tried to write to the developers and it moved me here can you assist me in seeing how i can see the error logs or the debugging?

**Comment by Dani2449** [comment]
i activated by force all and waited few days Look how many errors it gives (I am using Astar theme) - this template https://websitedemos.net/sierra-industry-02/

![image](https://github.com/woocommerce/action-scheduler/assets/122624042/9c443052-5615-4724-ae4f-1cdba169039b)

**Comment by barryhughes** [comment]
If I'm reading correctly, these are not "errors", exactly ... it's just that the queue is not being processed as promptly as we'd like and expect.

> it's strange it still repeating it i tried to write to the developers and it moved me here can you assist me in seeing how i can see the error logs or the debugging?

I don't really know anything about your local development environment—so it's a little hard to offer suggestions—and you may find it easiest to install a plugin that helps to surface error log messages (there [are a few](https://wordpress.org/plugins/search/error+log/) to pick from).

It may also be worth doing some basic troubleshooting. The screenshots suggest you are using WP Forms, and that plugin appears to use Action Scheduler. So, keep that active, and deactivate all other plugins (please also switch to a default theme, such as Twenty Twenty-Four). Does the problem clear up then? If so, it suggests a conflict of some kind.

> i am for now using the Local to have the wrodpress on my computer first this is why i want to fix it.

I'm a little curious if the root of the problem is simply that you are running your site locally, without any sort of reliable system scheduler integration, and so lack the traffic required to process the queue (which would lead to you periodically seeing unprocessed actions).

Also, to be clear, when you reference 'Local' do you mean [LocalWP](https://localwp.com) (...if so, you may wish to search their docs to learn how to access the logs)?

**Comment by Dani2449** [comment]
Hello barry

thank you you are very helpful.

yes, I am using LocalWP.

This is the plugin that I use
![image](https://github.com/woocommerce/action-scheduler/assets/122624042/8a5aa18c-5f4c-4bf2-ac99-bbc9e674e07c)

before it looked like it didn't appear because I used it for another website and it looks okay.


I thought also maybe because I using it locally and this is why it happened.

I with try with a different theme and come back to you.

I added https://wordpress.org/plugins/error-log-monitor/ to check let see what it gives us

**Comment by Dani2449** [comment]
I hope i configured it correctly i put it in the 

![image](https://github.com/woocommerce/action-scheduler/assets/122624042/ad969dbe-f67e-48fd-a3da-f35453b82553)


and i put this code here
![image](https://github.com/woocommerce/action-scheduler/assets/122624042/98faab55-6c20-405a-893c-367360d298d1)

**Comment by Dani2449** [comment]
still look its there but i have the debugger i am putting it here maybe you can help me with it please.
[error.log](https://github.com/user-attachments/files/15900558/error.log)

**Comment by barryhughes** [comment]
Many of the errors seem to relate to Elementor, or else Image Optimizer. It's not impossible they are surfacing when the queue is being processed, and causing difficulties there.

Regarding LocalWP, I don't use this myself but I understand you can register cronjobs in the container, and you could use these to trigger WP Cron with a rule looking something like this (just an example ... you would need to correct the path, etc):

```
* * * * * wp --path=/path/to/wordpress cron event run
```

That might get things running locally. Or, if you are not comfortable with that, you could perhaps install [WP Crontrol](https://wordpress.org/plugins/wp-crontrol/). This could help you to understand if the problem is exclusive to Action Scheduler, or if WP Cron in general is having problems running in your local site (which is what I suspect).

**Comment by barryhughes** [comment]
Since this sounds like a problem with a particular local development setup, rather than a bug in the plugin itself, I'm going to go ahead and close.

**Comment by zhenju84-debug** [comment]
I also come up wih this issue, the past due action is not able to be deleted and it could generate a lot more actions after a while. 

This migration hook action is always there. This is quite annoying.
