### ISSUE TITLE
Question: Action ordering and concurrency / dependent tasks?

### ISSUE THREAD

**Issue by myndzi** [Prospress/action-scheduler#1065]
I have some slow external APIs to interact with and potentially large batch processes to execute. I've been looking into ways that I can break the work up into smaller chunks and execute them in the background over time. However, I want to ensure that things happen in a certain order. For example, if I am importing a set of 6000+ products from a remote source, I only want to run the step that removes any stale entries after I know that I've successfully completed the import.

The documentation does a good job of explaining some of how Action Scheduler works, but leaves me with some questions about how concurrency and ordering of enqueued actions works.

> If there are actions to be processed, Action Scheduler will stake a unique claim for a batch of 25 actions and begin processing that batch.

This suggests to me that it's possible for multiple batches to be claimed and running at the same time (I saw reference to a default concurrency of 5 somewheer while looking), which means that there's a possibility for a series of actions that have been scheduled to be broken into two separate batches and run out of order.

> as_schedule_single_action() & as_schedule_recurring_action() can accept a $group parameter to group different actions for the one plugin together.

This is a little unclear. What does it mean to "group actions together"? I can't seem to find anything explaining exactly what `$group` is for.

Edit: Same question with `$unique`. The documentation doesn't explain what this argument _means_. I'm guessing that you cannot enqueue a unique task if there is already one scheduled or in-progress?

It'd be nice if the API documentation includes a section explaining the semantics of the arguments.

Overall, I'm hoping that I can rely on a library to allow me to queue up related tasks and ensure that they can only execute in a defined order. Is that possible?

One approach I can think of is to avoid scheduling the tasks up front, and instead schedule individual synchronous operations in some action handler that passes data forward. So, I might schedule "import batch 1 of 5", and in the action I then schedule "import batch 2 of 5" and so on. That feels a bit unwieldy to write, but maybe it's the best way to go?

**Comment by jorgeatorres** [comment]
Hi @myndzi! 👋 

Thanks for reaching out and for pointing out some gaps in our documentation. I'm going to try to answer your questions and will also create an issue in our repo so that we don't forget to improve the docs on those topics.

> However, I want to ensure that things happen in a certain order. For example, if I am importing a set of 6000+ products from a remote source, I only want to run the step that removes any stale entries after I know that I've successfully completed the import.

Without knowing the specifics of your use case, our suggestion would be  that you might be better served with just _one recurring_ action that progresses through the batch and eventually either performs the cleanup itself or schedules a non-recurring action to do the cleanup. If you want to take advantage of processing multiple products "at the same time" then you might still have just one recurring action that splits the batch between various actions, schedules them and also schedules a possibly recurring action.
I guess what I'm trying to convey here is that it's perfectly possible for a scheduled action (recurring or not) to schedule (or un-schedule) other actions (even itself) depending on data.

> This suggests to me that it's possible for multiple batches to be claimed and running at the same time [...]

This is correct. If you schedule N actions they might end up running at the same time.

> This is a little unclear. What does it mean to "group actions together"?

This is mostly for identification purposes. For example, all actions related to the same plugin might use the same group name. Also, when running Action Scheduler jobs via WP-CLI, we support running _all jobs_ from the same group, for example.

Groups don't necessarily mean that the actions will run together or in any particular order within the group.

> Same question with $unique. The documentation doesn't explain what this argument means. I'm guessing that you cannot enqueue a unique task if there is already one scheduled or in-progress?

Pretty much, yes. Actions with the same name and group name won't be scheduled again if `$unique` is used.

> Overall, I'm hoping that I can rely on a library to allow me to queue up related tasks and ensure that they can only execute in a defined order. Is that possible?

As mentioned above, you could sort of do this by scheduling just one recurring action that progresses through the batch and performs the cleanup at the end, but then the responsibility of ensuring the correct order of operations will fall on that action's code.

> So, I might schedule "import batch 1 of 5", and in the action I then schedule "import batch 2 of 5" and so on. That feels a bit unwieldy to write, but maybe it's the best way to go?

This is pretty much what we've suggested above. A possible improvement, depending on how you poll for and identify batches, is that this recurring action might split a batch into multiple actions, and when it runs _again_ it could check whether those actions have all completed before progressing to any other phase.

- - - -

Hope the above helps. Let us know if you have any further questions!

**Comment by myndzi** [comment]
Thanks for the response and clarifications! It doesn't seem like this library is the choice if I want to avoid writing the coordination logic myself. I think billing itself as a "job queue" (where "queue" is read with some ordering guarantees) is what threw me; I was looking for a way to use it in that fashion, but it doesn't exist. That said, just the ability to run a long-lived task conveniently is a boon, but I'll have to look closer at whether there's a reason not to just use wp cron itself before taking an extra dependency. I think the action / event status log may be super beneficial, for example.

For later readers, and in response to "specifics about my use case", I'll give a little extra context - you can skip this if you like, or consider if it is a meaningful use case for future work:

I'm integrating an external ERP system with a WooCommerce site. Certain pieces of information will have to be synchronized, including certain product info and orders. There are a couple different use-cases:
- Regular bulk updates; this needs to be batched due to slowness and API limits (e.g. send product price and description changes to the ERP system, receive stock quantities)
- Targeted updates (e.g. in a hook after updating a product in WC, or completing an order)

Ideally, I want to have some amount of coordination, so I want to _enqueue_ a targeted update to occur _after_ any currently-running batch update. I also want to be able to run the batch updates over time so I don't, for example, hit a PHP timeout if the full update takes too long. The ability to retry / re-enqueue a couple times if one request fails temporarily (say, a 500 error) would be nice too.

So, I was looking for something that would let me (at the time I want to initiate some action) enqueue _all the future work_ atomically and block anything that involves the same data until it's complete (in other words, push a number of tasks into a single queue and then consume from it over time), without having to write my own coordination or locking behavior, install an actual queue service, etc.. I've previously found <https://github.com/deliciousbrains/wp-background-processing> for doing background task execution as well, but since action scheduler is part of WooCommerce(?) I may be able to reduce my dependencies by selecting this library. In either of those two cases, it looks like I'm still writing my own coordination logic, but it may be that all I really need is a lock and the ability to delay or reschedule an action, which I can do.
