### ISSUE TITLE
Add --group option for WP CLI

### ISSUE THREAD

**Issue by thenbrent** [Prospress/action-scheduler#121]
Being able to run queues for specific groups of actions is valuable at scale. Why? Because it means you can restrict the concurrency for similar actions.

For example, let's say you have 300,000 actions queued up comprised of:

* 100,000 renewals payments
* 100,000 email notifications
* 100,000 membership status updates

Action Scheduler's default WP Cron queue runner will process them all together. e.g. when it claims a batch of actions, some may be emails, some membership updates and some renewals.

When you add concurrency to that, you can end up with issues. For example, if you have 3 queues running, they may all be attempting to process similar actions at the same time, which can easily lead to querying the same database tables with similar queries. Depending on the code/queries running, this can lead to database locks or other issues.

If you can batch based on each action's group, then you can improve performance by processing like actions consecutively, but still processing the full set of actions concurrently.

For example, if one queue is created to process emails, another to process membership updates, and another to process renewal payments, then the same queries won't be run at the same time, and 3 separate queues will be able to run more efficiently.

The WP CLI runner is a good opportunity to implement this. It will almost certainly become the most recommended option for larger stores, which are the ones who will most need this option.

**Comment by JPry** [comment]
@thenbrent 

I did a quick perusal of the code, and it looks like the grouping of actions isn't implemented when fetching actions using the store. In other words, we don't currently have a way to stake a claim for actions based on a particular group.

I mention this because it looks like this would require some changes to the store and queue runners to enable the ability to select actions based on group. The methods that I can initially see that would need updates are:

* `ActionScheduler_Store::stake_claim()`
* `ActionScheduler_Store::claim_actions()`

If we're going to be bringing on a major release with breaking changes anyway, I think it's reasonable to get this added in at the same time, as it could have benefits elsewhere besides WP CLI.

I'm interested in any additional thoughts you might have.

**Comment by thenbrent** [comment]
> If we're going to be bringing on a major release with breaking changes anyway, I think it's reasonable to get this added in at the same time

Agreed.

> The methods that I can initially see that would need updates are:

I does look like those are the only two which will require updates, fortunately.

At first glance, it appears adding a new param to both to specify a group should be sufficient, so that's not a major change (but it might provide more involved than that).

If that's the case, then it's definitely worth doing still. But if you find it's more involved once you dive in, we can always reevaluate.
