### ISSUE TITLE
Handle SiteGround max execution time better

### ISSUE THREAD

**Issue by thenbrent** [Prospress/action-scheduler#149]
SiteGroud shared plans enforce a 120 second max execution time. That's plenty of time, so we don't see many issues, but we should still prevent any issues (see #108 for deeper background).

Now that #134, we have all the scaffolding in place for handling this timeout. We just need a way to detect if plugin code is running on SiteGround.

e.g. with WP Engine, we check `defined( 'WPENGINE_ACCOUNT' )`, with Pantheon `defined( 'PANTHEON_ENVIRONMENT' )`, but I don't know of a way to do it with SiteGround.

I asked SiteGround technical support about this, and they advised me there was no way for them to detect what code was running on a site… the opposite of what I was asking. :upside_down_face: 🙂

So I've asked in Post Status Slack now and will update here if I get an answer.

Props @jrick1229 for finding the max execution time.

**Comment by JPry** [comment]
I reached out to @salcode, as I know he has some sites on Siteground, to see if he knew of any environment variables we could look at. He said:

> Looking through the environment variables, the only thing that might be useful is the `HOSTNAME` env variable is `m35.siteground.biz`.  I'm guessing you could check if the `HOSTNAME` contains `.siteground.`

I think checking the host name could be a reasonable solution.

**Comment by thenbrent** [comment]
Thanks @JPry 🙇 

On Post Status Slack, I also got the following two answers: 

> They have WP caching stuff that may be a “worst case try to see if it’s siteground”
> ^ true, they have an MU plugin for their supercacher iirc

So for that, we could potentially check if a Super Cacher function exists.

> Siteground sites set `wpSGCacheBypass` cookie https://publicwww.com/websites/wpSGCacheBypass/

**Comment by salcode** [comment]
Just wanted the chime in

> They have WP caching stuff that may be a “worst case try to see if it’s siteground”
^ true, they have an MU plugin for their supercacher iirc

None of my Siteground sites have this plugin in `mu-plugins`.  I believe they rebranded the "Super Cacher" plugin as [SG Optimizer](https://wordpress.org/plugins/sg-cachepress/).  All of my sites **are** running this plugin (not as an `mu-plugin`) but I don't think it is required.

> Siteground sites set wpSGCacheBypass cookie https://publicwww.com/websites/wpSGCacheBypass/

On my site, I'm only seeing this cookie set when I'm logged in.  Since it appears to bypass the cache, it makes sense for those logged in to skip the cache but not for everyone.  Though this does not explain why it appears in so of the sites at https://publicwww.com/websites/wpSGCacheBypass/

**Comment by thenbrent** [comment]
Thanks @salcode, that's very helpful! 🙇
