### ISSUE TITLE
Add --hook option for WP CLI

### ISSUE THREAD

**Issue by thenbrent** [Prospress/action-scheduler#160]
https://github.com/Prospress/action-scheduler/issues/154 is awesome, but once it came down to implementing support for it in Subscriptions with https://github.com/Prospress/woocommerce-subscriptions/pull/2740, I realised claiming based on hook could be just as valuable (if not more so) than claiming by group.

This is effectively the strategy taken in https://github.com/Prospress/woocommerce-subscriptions/pull/2740.

However, we could achieve this in Action Scheduler core with code very similar to that introduced in https://github.com/Prospress/action-scheduler/pull/154, which would negate the need for any changes to Subscriptions (or other plugins), and also be fully backward compatible for hooks previously scheduled without a group.

**Comment by james-allan** [comment]
I’ll leave the final decision up to you guys but for what it’s worth I like this idea. 

The main reason is because it means sites can run specific queues in parallel via WP CLI from day 1 rather than having to wait for all subscription-related events to be rescheduled in the future and be created with a group.

The other reason I like this is for the reasons explained on Prospress/woocommerce-subscriptions#2740. By setting each action’s group to the hook, you end up with a lot of uniqueness but without the option to capture multiple groups within the 1 queue runner. In a WCS context, there aren’t a lot of natural groups I can think of beyond perhaps cache updates and anonymisation. There's no reason at the moment that I can think of for running all different type of cache updates in the one queue when you could run them separatly but by having the option to claim by hook and claim by group, we leave our options open if we do decide to go down the route of adding more general groups.

It will also allow third-parties using groups already to keep their existing groups while still being able to run specific events in the one queue.

**Comment by thenbrent** [comment]
Done with #161, which added new `--hooks` flag.
