### ISSUE TITLE
Add complete code examples to README

### ISSUE THREAD

**Issue by bennygill** [Prospress/action-scheduler#204]
After going over the README file many times I'm still confused about how to implement this plugin.

Can someone please elaborate using code examples?

For example, how would I queue up these simple tasks for batch processing?

```
$lower_case_names = array('mary', 'bob', 'trent', 'bill', 'jane');

function make_names_uppercase ($lower_case_names) {
    $upper_case_names = array();
    foreach ($lower_case_names as $name) {
        $upper_case_names[] = strtoupper($name);
    }
    return $upper_case_names;
}
```

Related SO question: https://stackoverflow.com/questions/52852984/how-to-use-the-action-scheduler-wordpress-job-queue

**Comment by thenbrent** [comment]
Hi @bennygill, to run `make_names_uppercase()` via Action Scheduler, you need to:

1. add an action/hook to the queue, like this:

```
$names = array( 'mary', 'bob', 'trent', 'bill', 'jane' );

// Schedule an action name 'make_names_uppercase_action' with specific first name data
as_schedule_single_action( time(), 'make_names_uppercase_action', array( 'names' => $names ) );
```

2. then attach your `make_names_uppercase()` function to that schedule action like this:

```
add_action( 'make_names_uppercase_action', 'make_names_uppercase', 10, 1 );
```

`make_names_uppercase()` will then receive one parameter, the `$names` array when Action Scheduler triggers the `'make_names_uppercase_action'` hook.

Thanks for letting me know that wasn't clear in the README. Let me know if it's clear or not, and once I know, I'll update the README with usage examples.

**Comment by bennygill** [comment]
Thanks @thenbrent that helps a lot :)

Here is my re-take on the code example, please tell me if I missed anything:

```
//Create a "schedule action" and attach it to a new action hook (defined below)
as_schedule_single_action( time(), 'your_new_action_hook', $some_argument_for_your_function );

//Create a WordPress action hook and attach it to the function you need to batch process
add_action( 'your_new_action_hook', 'your_batch_process_function', 10, 1 );

//Create a function that contains all the logic you want to batch process in the background
function your_batch_process_function ($some_argument_for_your_function) {
 	//Do stuff here
}
```
Some questions:

1) I'm confused why I need to pass `as_schedule_single_action` the same variable (`$some_argument_for_your_function`) as my function. Did I get that part right?

2) In the first example you passed `as_schedule_single_action` the `$names` array inside another array like `array( 'names' => $names )`. Does that mean the `as_schedule_single_action` argument always has to be an array? Or can I pass in ints and strings?

**Comment by bennygill** [comment]
Here's an alternate code example with looping, is this right?

```
//Create a "schedule action" and attach it to a new action hook (defined below)
as_schedule_single_action( time(), 'your_new_action_hook', $some_variable );

//Create a function that loops over tasks sends them for batch processing
function your_batch_process_function ($some_argument_for_your_function) {
	for ($i = 0; $i < 10; ++$i ) {
		 //Create a WordPress action hook and attach it to the function you need to batch process
		add_action( 'your_new_action_hook', 'do_stuff', 10, 1 );
		do_stuff ($some_variable);
	}

function do_stuff ($some_variable) {
	//Some logic task here that takes a while to process
}
```

**Comment by thenbrent** [comment]
> I'm confused why I need to pass `as_schedule_single_action` the same variable ($some_argument_for_your_function) as my function.

You need to pass ``as_schedule_single_action()` the args which will be passed to any callbacks on the hook. 

Think of `as_schedule_single_action()` as being equivalent to WordPress core's `do_action()`, only with a delay in when that `do_action()` is called. If you're not familiar with `do_action()` or the Hooks API in WordPress, that is definitely required knowledge for working with Action Scheduler, so it's read up on them here: https://developer.wordpress.org/plugins/hooks/

> Did I get that part right?

Yes, as long as the values of `$var_passed_to_function` and `$var` are right. `$var_passed_to_function`  needs to be an array of parameters to pass, so `$var` should be the first value of that array.

> Does that mean the `as_schedule_single_action` argument always has to be an array? Or can I pass in `ints` and `strings`?

As above, it has to be an array with each value representing one of the parameters passed to the callback.

> Can I loop through something and send lots of tasks for processing using as_schedule_single_action()? I assume that sending them with time() means "batch process these tasks as soon as you can".

Yep for sure. And yep, that's what it means.

By default, they will be processed as soon as the `'action_scheduler_run_queue'` action is triggered by WP Cron.

If you need them processed faster than that, you can set up WP CLI tasks to run scheduled actions more frequently.

> Here's an alternate code example with looping, is this right?

Close, but you'd probably do it like this instead:

```php
//Create a function that loops over tasks and sends them for batch processing
function your_batch_process_function() {
	$do_stuff_variable = 'blah blah';
	for ($i = 0; $i < 10; ++$i ) {
		// Create a "schedule action" for the data
		as_schedule_single_action( time(), 'your_new_action_hook', $do_stuff_variable );
	}
}

// Attach to the function you need to batch process
add_action( 'your_new_action_hook', 'do_stuff_function', 10, 1 );

// The function that will be processed in the background
function do_stuff_function ($x) {
	//Some logic task here that takes a while to process
}
```

Then call `your_batch_process_function()` somewhere as needed to kick off the scheduling.

A lot of this is outside the scope of using Action Scheduler, and is more closely related to how PHP processes code, and the WordPress Hooks API. I won't be able to help with the more fundamental concepts more. I'll try to point you in the right direction for required reading though. :)

**Comment by bennygill** [comment]
Thanks!
I think that has everything up for me :+1:

**Comment by thenbrent** [comment]
Hi @bennygill,

> Can someone please elaborate using code examples?

I've moved the README to its own site now, as it was getting a little too long for one page.

On that site, I've added some of the above info and a new _Usage_ section with an example showing everything needed to schedule a (recurring) action.

You can find that here: https://actionscheduler.org/usage/#scheduling-an-action

Let me know if you think that example isn't clear enough to help other folks coming to Action Scheduler and I'll see what I can do to improve it. :)

**Comment by gavin310** [comment]
It would really help to include in the example how to pass $args. From trial and error I've gathered that the args array should contain one key, and that keys value is what will be passed. Other key=>value pairs will be ignored. Why not just pass the entire $args array?

**Comment by ThinkingFox** [comment]
@gavin310 

> It would really help to include in the example how to pass $args. From trial and error I've gathered that the args array should contain one key, and that key's value is what will be passed. Other key=>value pairs will be ignored. Why not just pass the entire $args array?

you've probably figured this out a long time ago so this is more of a help to anyone else hitting the same issue and not spotting what they're doing wrong.

`as_schedule_single_action( time(), 'your_new_action_hook', $do_stuff_variable );` 
The example from @thenbrent above is only pulling a single args variable across. Even if you stuff the $do_stuff_variable with all sorts of goodies you'll only ever get the first key. And it's no good trying to loop through the resulting array as it only has the single key. Much head scratching ensued!

Lightbulb moment:

I was struggling to get my head around it too until I came across a post by Sanjeeb Aryal and twigged why I was having the same issue with passing multiple args.

To pass multiple variables you need to pass them inside an array like this:
`as_schedule_single_action( time(), 'your_new_action_hook', array($variable_one, $variable_two, $variable_three );`

then, instead of the action looking like this: 
`// Attach to the function you need to batch process
add_action( 'your_new_action_hook', 'do_stuff_function', 10, 1 );` we need to tell it to expect more than 1 args like this:

`// Attach to the function you need to batch process
add_action( 'your_new_action_hook', 'do_stuff_function', 10, 3 );`

and your actual function changes to this:
`function do_stuff_function ($variable_one, $variable_two, $variable_three) {
//Some logic task here that takes a while to process
$someotherthing = $variable_one;  // etc
}`

(Apologies for fat-fingered typing, poor code layout, and sloppy var naming)

First time trying to set up action scheduler and it was driving me mad until I saw the post from Sanjeeb and even then I was scratching my head until I spotted the change from 1 to 3. Doh!

Link to Sanjeeb's post here: [https://sanjeebaryal.com.np/scheduling-the-tasks-with-action-scheduler/](https://sanjeebaryal.com.np/scheduling-the-tasks-with-action-scheduler/)

 happy scheduling 👍
