### ISSUE TITLE
Detect action is run manually (admin, cli, etc.) and not by the scheduler?

### ISSUE THREAD

**Issue by alexminza** [Prospress/action-scheduler#218]
Running the action manually can be considered as an override and to have different behavior (force run, etc.)

Is there a way to detect this in code?

**Comment by alexminza** [comment]
@JPry one possible use case would be marking the manual triggering of an action as a 'forced' run.

For example, for a payment gateway there are some checks implemented so that the daily midnight scheduled action does not run 'too soon' if it did not have the chance to run as scheduled. However, manually triggering the action would override this check.

**Comment by thenbrent** [comment]
@alexminza while what @JPry mentioned above is correct - there isn't a way to detect how an action is run yet - if you require this, please feel free to submit a PR and we'll review it.

For some staters - `ActionScheduler_ListTable::process_row_action()` is responsible for manually running the action. It calls `$this->runner->process_action( $action_id )` to handle the `run` command.

Because the queue runner is injected into `ActionScheduler_ListTable` via `__construct()`, it would therefore be possible to implement a custom `ActionScheduler_QueueRunner` instance that implements the logic you require in its `process_action()` method.

For now, I'll close this issue and we can reopen it if you decide to submit a PR and it needs further discussion.
