### ISSUE TITLE
Failure Handling

### ISSUE THREAD

**Issue by alanef** [Prospress/action-scheduler#234]
Hi, excuse my noob question but I have searched, but couldn't find clarity.

If I have a job that may time out or fail for other reasons, is there anything extra I have to do?

My code - 'self recovering' as in it keeps track with a list in a transient so if it is restarted it doesn't start from the beginning again.   But is there anything else?

When I manually tested with a 'kill' in the middle, the job just went in to 'in progress' and stayed there. Is there anything I have to do to restart an in progress job or does the scheduler handle that?

**Comment by thenbrent** [comment]
Hi @alanef :)

> the job just went in to 'in progress' and stayed there.

It will have been marked as `failed` 5 minutes or so after it hung, as long as another queue was run. Details on that code here: https://github.com/Prospress/action-scheduler/blob/dd49ca6/classes/ActionScheduler_QueueCleaner.php#L101-L127

> Is there anything I have to do to restart an in progress job or does the scheduler handle that?

Action Scheduler doesn't re-run hung jobs. This is because it really has no idea what is done as part of the scheduled action and/or where the job hung.

For example, Action Scheduler is used by WooCommerce Subscriptions to process payments - Subscriptions definitely doesn't want AS re-scheduling a hung payment action if the payment was processed, and an error occurred after that, because it would could create an infinite loop on payments.

It is possible to re-schedule your job though when it is marked as `failed` by the Queue Cleaner. 

You could do that with something like:

1. attach a callback to `'action_scheduler_failed_action'`
1. in that callback, initialise the an action from the `$action_id` using `ActionScheduler::store()->fetch_action( $action_id )`
1. check if the action's hook is the one you are scheduling via `$action->get_hook()`
1. check if the action should be rescheduled (or if everything it needed to do has been redone)
1. if needs rescheduling, schedule a new instance with the same args via something like this:

```php
as_schedule_single_action( 0, $action->get_hook(), $action->get_args(), $action->get_group() );
```

**Comment by alanef** [comment]
Hi Brent,

Thanks for your explanation, firstly the 'hung state of my job was due to the cron setup in my test environment not firing the queue.

Thanks for your explanation of detecting and rescheduling failed jobs, however, it might be that I have misunderstood the ideal design, perhaps rather than create a job that can be restarted that stores a list of actions within a transient and loops through that transient deleting processed items, I should have a repeating process that creates a  large number of single action events for the scheduler.

So for example
- once nightly - list all files in a directory and create an action schedule per file
the action per files then processes the desired action individually, this will create thousands of short actions ( 2 second ish )

**Comment by thenbrent** [comment]
> I should have a repeating process that creates a large number of single action events for the scheduler

This is generally a better design, because it means you get traceability on each job, like the status, and run time (via action started/action complete log messages).

> this will create thousands of short actions.

The only gotcha here is that AS still uses Custom Post Types, which don't scale into the 100,000s of jobs very well with WordPress < 5.1. Once WP 5.1 is released, it will scale better, and in AS version 3.0 (no ETA on that yet), we will introduce custom tables to make it even more performant.

**Comment by alanef** [comment]
Sorry if this is a bit of a lazy question, but finally, how would you handle an end of batch process
e.g.
-  Repeating daily job queues 1,000 single actions
- 1,000 single action complete
- At the end  - analyse the results of the 1,000 actions and send a summary email

My thoughts are, perhaps  create a subgroup for the 1,000 actions e.g. {plugin-name}-task
The hook into  action_scheduler_after_process_queue
and at that point, some how, check that all action in {plugin-name}-task are either complete or failed - if so - send email

Or is there a better way?

**Comment by thenbrent** [comment]
> My thoughts are

That sounds like the most sane way to do it. Slightly inefficient with the queries, but likely the most reliable way, and more efficient than running that query after all 1,000 jobs.

The one gotcha is that if there is a fatal error on the final action, the email won't be sent unless there is at least one other job to process in another queue. And that could also be scheduled for some time after.

> An alternative I thought would be queue the 999 and then queue the 1,000'th with an arg

Something like that will work to. You still have the issue with the fatal error on the final action though.

The other option is to schedule a 1001'th action to run 1 second after the other 1000, then in a callback on that action, check that all actions in `{plugin-name}-task` are either `complete` or `failed`. If they aren't, reschedule the same task for some time in the future (you could even base this on the number of pending `{plugin-name}-task` that remain to be more peformant), and the process will repeat.

**Comment by alanef** [comment]
Sorry, back again.

Are jobs started in sequence?

So my batch run has a pre batch preparation step
the batch
the  end of job email

Now I have already identified that in the middle batch, it is best to group tasks, as 10,000 individual actions is slower than 10 action of 1,000

However the pre batch process makes some API calls which if I included them simply in the 10,000 sub actions would take ages ( repeating the same calls redundantly )

So pre batch - I will make the API calls and store the results in a transient, however I can't guarantee my pre batch calls will complete before time out - so therefore I can split them into some 60 or so  API actions.

The problem is know when to queue  the main batch   ( and after the mail batch the email )

So IF the actions do run sequentially, is it possible to just queue the pr-batch and then queue the generation of the main batch ( say 5 minutes later )  - or should I devise some sort of of custom job dependency control?
