### ISSUE TITLE
Performance question...

### ISSUE THREAD

**Issue by n9yty** [Prospress/action-scheduler#235]
Forgive me if I'm totally off the path here, but I was looking for another problem and came across a query being generated by action scheduler that seems to be a bit of a performance issue here....

It generates a query like this:

SELECT p.ID FROM wpscm_posts p WHERE post_type='scheduled-action' AND p.post_status='publish' AND p.post_modified_gmt <= '2019-01-09 20:24:10' ORDER BY p.post_date_gmt ASC LIMIT 0, 20

If I run that, it takes from 3-5 seconds to sometimes over 10 or more. Typically it is ~3 seconds if I do a FLUSH QUERY CACHE; RESET QUERY CACHE; first.  But on a cold invocation it can take quite a bit more.

If I simply change the ORDER BY from using post_date_gmt to post_date, it goes to <50ms.  This is most likely because there is an index on post_date but not on post_date_gmt, or so I guess.

In running it multiple times it is almost always <15ms with this change, so that is quite a contrast to the 3s times.

Since it is only sorting, why would post_date_gmt be preferred over post_date?

UPDATED: In thinking it through a bit more, if your site changed time zones, or daylight savings time, I can see why sorting by post_date_gmt could have the advantage. But the performance... Would creating an index be worthwhile here?  Stranger, there is one, so why the big change in speed? Is it local to our site? :(

**Comment by n9yty** [comment]
Seems it was a DB error here... I forced the index to rebuild and now it is equal in performance. Sorry for the noise.

**Comment by thenbrent** [comment]
> if your site changed time zones, or daylight savings time, I can see why sorting by post_date_gmt could have the advantage.

Yep, that's it exactly. :)

However, I see your point when it's for the ORDER BY. Especially given the query you posted should probably be ordering by `post_modified` or `post_modified_gmt` rather than `post_date_gmt` or `post_date`.

> Would creating an index be worthwhile here?

It sounds like it would on your site with those query times, depending on how large the table is.

That would be a quick fix, but as above, I do wonder if perhaps the order by should be something else anyway.

> Stranger, there is one, so why the big change in speed? Is it local to our site?

It's likely because you have a large number of entires in the posts table, like orders, subscriptions, or some other custom post types.

The ultimate plan to address this (and related issues) is to move to use well indexed custom tables. That's 90% done and slated to be included in AS core with v3.0 (which doesn't have an ETA yet, but will be this year). You can keep track of progress on that on #77. :)
