### ISSUE TITLE
Simple background job processor

### ISSUE THREAD

**Issue by robskrob** [Prospress/action-scheduler#250]
Is `action-scheduler` just for scheduling background jobs to run at some point in the future? Can it also serve as simple asynchronous processing? In other words, I would just like to add a job on a queue and for something to pick up the work that I enqueued. The work does not necessarily need to be done at a particular time. The work just needs to be done as soon as possible. The only project I've found like this is [bernard](https://github.com/bernardphp/bernard) -- which only processes jobs in the background. I do not think there's any scheduling with `bernard`. 

At the end of the day, I just want to offload work (DB writes, HTTP requests etc...) from the `apache` process to another process so `apache` gets a break and does not become a bottleneck. I do not necessarily care if the work gets done on Tuesday night at midnight or every 30 minutes -- just as long as the work gets done as soon as it can get done.

**Comment by thenbrent** [comment]
The short answer is yes, you can just schedule a job to run asycnhornous, just schedule it for `time()`. That's saying "run this now" so Action Scheduler will run it as soon as possible.

This is how [`WC_Action_Queue::add()`](https://github.com/woocommerce/woocommerce/wiki/WC_Queue---WooCommerce-Worker-Queue#adding-jobs-to-the-queue) works in WooCommerce core.

The longer answer is that there isn't an API exposed for asynchronous processing yet because if/when we provide that, we want to have some kind of guarantee that the job will be run in some very near amount of time.

That requires two things:

1. Action Scheduler to run a queue ASAP for async jobs, not just whenever WP Cron runs another queue, which may be one or more minutes in future
2. the async jobs to have some kind of priority over scheduled jobs, at least in the async runner, so that even if there are 100 scheduled jobs for a date in the past, the aysnc jobs still process ASAP

Both of those things are fairly easy to achieve. At the very end (shutdown) of any request where an async job is queued, AS could trigger a HTTP request that initiates a queue in another request exclusively for processing async jobs.

We already have code that does something very similar to the first part of this in the [high volume plugin](https://github.com/Prospress/action-scheduler-high-volume/blob/e2feaaca41df742e7f912b62/action-scheduler-high-volume.php#L78-L99), which uses HTTP requests to process additional runners. We'd just need a new `ActionScheduler_Abstract_QueueRunner` instance to process on those requests.

**Comment by robskrob** [comment]
@thenbrent thank you for this detailed reply.

**Comment by gavin310** [comment]
I tried adding a job set to `time()` and it still takes on average between 10-20 seconds for the job to run. Is this how it should function, or am I doing something wrong? Is it possible to have the job start immediately or closer to 1 or 2 seconds?
