### ISSUE TITLE
Comment type not always being filtered

### ISSUE THREAD

**Issue by rrennick** [Prospress/action-scheduler#320]
This is from a report that WooCommerce filters out order note and webhook comment rows in a query where AS is not filtering out the action logs. Here's the query from Query Monitor:

```
SELECT comment_approved, COUNT(*) AS num_comments 
FROM wp_comments 
WHERE comment_type NOT IN ('order_note', 'webhook_delivery') 
GROUP BY comment_approved
```

AS does have a filter on the comment feed at https://github.com/Prospress/action-scheduler/blob/master/classes/ActionScheduler_wpCommentLogger.php#L127. We should apply this filter to the same queries as WC does for order notes for any non AS comment queries.

**Comment by thenbrent** [comment]
> We should apply this filter to the same queries as WC does for order notes for any non AS comment queries.

I suspect this is a result of hardcoded comment types to be excluded in custom query in WC core, not the filtered queries in WP. I've asked Warren for confirmation though.

For completeness, inline with my P2 comment, the offending SQL appears to come from `WC_Comments::wp_count_comments()`, which is using `$wpdb->get_results()` directly and hardcoding the comment types to exclude rather than going via WP APIs, which is why the AS filters aren't being applied.

The best approach to address that would be to either:

1. add `'action_log'` to the excluded comment types in `WC_Comments::wp_count_comments()` alongside like `'order_note'` or `'webhook_delivery'`. This is quick, and will work, but brings more knowledge of AS into WC than it should have.
1. add a new filter in `WC_Comments::wp_count_comments()` that Action Scheduler can use to exclude its own `'action_log'` comment types from that query (like it does for WP queries). This is a better approach, as it allows us to continue to abstract AS data storage knowledge within AS.
1. modify the query in `WC_Comments::wp_count_comments()` to mirror WP APIs, ideally mirroring and applying `'comments_clauses'`, as I suspect there may be other code attempting to exclude itself from comment queries like that using `'comments_clauses'`, so applying that will improve compatibility with 3rd party extensions.

Importantly, if the 2nd or 3rd options are taken, then `ActionScheduler_wpCommentLogger::get_comment_count()` would also need to run a check to _only_ be applied when WC is not active, because it is run _after_ `WC_Comments::wp_count_comments()` and performs near identical functionality to it.

**Comment by thenbrent** [comment]
This has been addressed in WooCommerce core with https://github.com/woocommerce/woocommerce/pull/24071
