### ISSUE TITLE
Recurring schedule interval 0

### ISSUE THREAD

**Issue by rrennick** [Prospress/action-scheduler#340]
In the course of testing, switching branches, etc. I ended up with a recurring action that had an schedule interval of 0 and a start time of 0.

```
O:32:"ActionScheduler_IntervalSchedule":2:{s:49:" ActionScheduler_IntervalSchedule start_timestamp";i:0;s:53:" ActionScheduler_IntervalSchedule interval_in_seconds";i:0;}
```

With the async runner this was generating hundreds of new actions per minute. We should have something in place to ensure that the minimum reschedule interval is at least 60 seconds in the future.

One positive note is that the tables implementation handles 40K actions with no visible performance degradation.

**Comment by thenbrent** [comment]
Agreed. Adding a safeguard against that kind of infinite loop is extremely important.

> We should have something in place to ensure that the minimum reschedule interval is at least 60 seconds in the future.

I'd vote in favor of an exception being thrown when an interval of < 60 seconds is found, perhaps with a filter to allow lower thresholds for specific actions / schedule types. I think it's fair to "hard enforce" the 60 second limit through an exception by default though.

There's two places we should enforce this interval:

1. when creating a recurring action in `ActionScheduler_ActionFactory::recurring()` and 
2. when scheduling the next instance of a recurring or cron action in `ActionScheduler_ActionFactory::repeat()` (once #333 is merged to add it) to guard against corrupted data when rescheduling recurring actions.

The former can be enforced with a simple check like `$interval < MINUTE_IN_SECOND`.

The later should probably be a little more lenient and check if the 2nd next instance is also `< MINUTE_IN_SECOND` e.g.

```php
$schedule = $action->get_schedule();
$next     = $schedule->get_next( as_get_datetime_object() );

if ( is_null( $next ) || ! $schedule->is_recurring() ) {
	throw new InvalidArgumentException( __( 'Invalid action - must be a recurring action.', 'action-scheduler' ) );
}

$min_timestamp = gmdate( 'U' ) + apply_filters( 'action_scheduler_ minimum_recurrence_interval', MINUTE_IN_SECONDS, $schedule, $action );

if ( $next->getTimestamp() < $min_timestamp ) {
	$next = $schedule->get_next( as_get_datetime_object( '+1 minute' ) );

	if ( $next->getTimestamp() < $min_timestamp ) {
		throw new Exception( __( 'Invalid recurring schedule - next scheduled date must be at least one minute in the future.', 'action-scheduler' ) );
	}
}
$schedule_class = get_class( $schedule );
$new_schedule = new $schedule( $next, $schedule->get_recurrence(), $schedule->get_first_date() );
$new_action = new ActionScheduler_Action( $action->get_hook(), $action->get_args(), $new_schedule, $action->get_group() );
return $this->store( $new_action );
```

That's a little dangerous because it's incrementing the schedule silently. That's to avoid errors for Cron actions being run late on their scheduled date. But there may be other cases that is unexpected so the final code may need to throw a warning for that case.

> One positive note is that the tables implementation handles 40K actions with no visible performance degradation.

Thanks for the unintended perf testing! 😆

**Comment by james-allan** [comment]
Adding for posterity a comment following a discussion with @thenbrent IRL.

When downgrading from 3.0 to 2.2 this issue happened for me too. I had a bunch of scheduled actions with 0 intervals.

```
O:32:"ActionScheduler_IntervalSchedule":2:{s:49:"�ActionScheduler_IntervalSchedule�start_timestamp";i:1564629552;s:53:"�ActionScheduler_IntervalSchedule�interval_in_seconds";i:0;}
```

throwing an exception won't catch it in this case because it will only be caught in the new code and won't exist once the site is downgraded. 

IIRC, the fix is to revert the change which moved to different properties keys. We can keep them, but need to at least keep the old ones in incase of a downgrade so the old code still knows how to handle them.

**Comment by thenbrent** [comment]
I've submitted #345 to address this. I haven't added the exceptions, because the root issue is downgrading, and adding them to 3.0.0 won't address that.

The exceptions would still be a valuable safeguard however, so I'll keep this open even once #345 is merged. I just don't see them as being a blocker to tagging 3.0.0.
