### ISSUE TITLE
run the as_schedule_single_action right away

### ISSUE THREAD

**Issue by firmanpolyrific** [Prospress/action-scheduler#348]
if I want to run **as_schedule_single_action** right away when this triggered, what should I put on $timestamp parameter?

**Comment by thenbrent** [comment]
@firmanpolyrific you can use `time()`. However, Action Scheduler 3.0.0 is introducing a new Async action type which will be more appropriate for running actions right away.

Using the `version_3_0_0` branch, Async actions can be added via `as_enqueue_async_action()`.

That function doesn't require timestamp, because it will run "as soon as possible". There's no docs for it yet, but there is some more info on it here: https://github.com/Prospress/action-scheduler/pull/322

We expect to tax version `3.0.0-beta-1` within in a week based on the `version_3_0_0` branch.

**Comment by firmanpolyrific** [comment]
Thanks for quick response,

is it save to use **version_3_0_0** for production now?
can you give some example of how to use as_enqueue_async_action() may be the parameters that needed

**Comment by thenbrent** [comment]
@firmanpolyrific definitely not! If you need this in product, just use `as_schedule_single_action( time() ... )`. :)

I also wouldn't recommend using any of the betas or RC in production. This version is a major change that requires a lot of testing prior to being officially released (and ready for production).

**Comment by firmanpolyrific** [comment]
@thenbrent 

I use version 2 and got an error: 
PHP Deprecated:  Non-static method ActionScheduler_AdminHelp::add_help_tabs()

does it fixed as well on version 2 ? i see it only fixed on version 3

**Comment by thenbrent** [comment]
@firmanpolyrific use the `2.2.5` tag rather than `master` branch. That tag doesn't throw this notice.
