### ISSUE TITLE
Consider storing schedules in own tables

### ISSUE THREAD

**Issue by javorszky** [Prospress/action-scheduler#46]
Ref https://github.com/Prospress/action-scheduler/pull/45#issuecomment-164418500 and https://prospress.slack.com/archives/wc-subscriptions/p1449870110000096

(screenshot for those without access)

![](https://cldup.com/UGGoZDfuiA.png)

**Comment by thenbrent** [comment]
Closing this as it's already possible to use a separate table (or database entirely) on large sites which need it. [`ActionScheduler_wpPostStore`, the class which manages all storage](https://github.com/Prospress/action-scheduler/blob/master/classes/ActionScheduler_wpPostStore.php), is [already swappable](https://github.com/Prospress/action-scheduler/blob/master/classes/ActionScheduler_Store.php#L129).

A custom table doesn't make sense for 90-95% of sites using AS (at least not with Subscriptions), which is why AS defaults to `ActionScheduler_wpPostStore`.

**Comment by toddlahman** [comment]
@thenbrent To use an alternative storage, is all that needs to be done is to call a different custom class using the ```action_scheduler_store_class``` filter hook?

**Comment by thenbrent** [comment]
Yep, in theory, other than actually implementing that custom class (which is the vast majority of the work). From memory, I don't think the Admin UI won't work with a custom store yet, but if we ever seen people needing it, we can revise it to get it to work.
