### ISSUE TITLE
okay to bundle into a plugin?

### ISSUE THREAD

**Issue by thomasplevy** [Prospress/action-scheduler#57]
Hey there,

This plugin is beautiful! I came across it after reading through some of the WooCommerce Subscriptions codebase (which looks like it was developed by some of the main contributors of this plugin).

I'd like to use the library in [LifterLMS](https://github.com/gocodebox/lifterlms) but I wanted to ensure this would be acceptable usage according to the developers. I don't see anything in the readme or any existing issues and there's no license.

Thanks,

**Comment by javorszky** [comment]
Hiya,

It's open source, you're free to do what you want with it. That said, we're currently fixing a few fairly serious issues. I'd suggest waiting until the 3 PRs get merged (#43, #54, #56), and then use the `bleeding_branch` branch to include it in your plugin.

The reason for that is because that's the most up to date version, and allows the most flexibility going forward (for example using a high performance storage engine instead of storing the actions as custom post types in WordPress).

Hope that helps

**Comment by thomasplevy** [comment]
@javorszky thanks for the information and thanks for the incredible-looking project. I'm excited to start messing with it.

Take care,
