### ISSUE TITLE
Disable cron after continew execute action schedule.

### ISSUE THREAD

**Issue by rvpatel** [Prospress/action-scheduler#59]
define( 'DISABLE_WP_CRON', true );
I have applied this setting in wp-config.php (localhost - xampp ) But action schedule working continue for recurring schedule.

**Comment by thenbrent** [comment]
@rvpatel Action Scheduler is started exclusively via WP-Cron. You may have something else starting WP-Cron, or you may not have disabled it correctly. 

Install the WP-Crontrol plugin https://wordpress.org/plugins/wp-crontrol/ and you will be able to view confirm if WP-Cron is actually blocked by visiting the **Tools > Cron Events** administration screen. If WP-Cron has been correctly blocked, you should see a number of scheduled events due to run "now" with a scheduled date in the past, like this: https://cloudup.com/chZshZUcGIe
