### ISSUE TITLE
MYSQL Unsafe Statement Warning.

### ISSUE THREAD

**Issue by kymcarlsson** [Prospress/action-scheduler#62]
Hi there,

Getting the following warning msg from MYSQL when running wp-cron every 30 seconds.
Here's the out output from /var/log/syslog:

`Oct  5 13:27:01 mysite CRON[7843]: (root) CMD (curl https://mysite.example.com/wp-cron.php > /dev/null 2>&1)
Oct  5 13:27:01 mysite CRON[7844]: (root) CMD (( sleep 30; curl https://mysite.example.com/wp-cron.php > /dev/null 2>&1 ))
Oct  5 13:27:31 mysite mysqld: 2016-10-05 13:27:31 140383028554496 [Warning] Unsafe statement written to the binary log using statement format since BINLOG_FORMAT = STATEMENT. The statement is unsafe because it uses a LIMIT clause. This is unsafe because the set of rows included cannot be predicted. Statement: UPDATE wp_posts SET post_password = '5b7d94922c5f856fe2a1', post_modified_gmt = '2016-10-05 13:27:31', post_modified = '2016-10-05 13:27:31' WHERE post_type = 'scheduled-action' AND post_status = 'pending' AND post_password = '' AND post_date <= '2016-10-05 13:27:31' ORDER BY menu_order ASC, post_date ASC LIMIT 25`

**Comment by thenbrent** [comment]
Hi @kymcarlsson that's caused by MySQL configuration.

If you're not using binary logs for anything, it's not really an issue. If you are using them for replication or recovery, you should change the `binlog_format` MySQL option on your serves to either `MIXED` or `ROW`.

More details:

 * https://www.psce.com/blog/2012/04/17/why-a-statement-can-be-unsafe-when-it-uses-limit-clause/
* http://dev.mysql.com/doc/refman/5.7/en/binary-log-setting.html
