### ISSUE TITLE
Earlier than expected timeout on hhvm

### ISSUE THREAD

**Issue by rsouthgate** [Prospress/action-scheduler#65]
My setup:
Nginx -> HHVM via fastcgi socket
DISABLE_WP_CRON set to true and a real cron job using wget to get wp-cron.php every 5 minutes.

In the code I see two timeouts; an internal five_minutes (by default) timeout and an actual process limit of 10 minutes (by default) passed to set_time_limit for the entire process. So I assume jobs still running after 5 minutes that are marked as timed-out internally may still complete within another 5 minutes.

I have a lot of actions scheduled for the same time every night (3am... typically all are completed by around 5 am) But I see various scheduled actions fail. When checking back in the logs I see the following message immediately after a slow query log related to the action:

Fatal error: entire web request took longer than 120 seconds and timed out

I have googled around whether HHVM respects the set_time_limit defined by the process and I can see no one saying it doesn't but I cannot work out where the 120 second timeout would be coming from. HHVM docs say hhvm.server.request_timeout_seconds default is to not timeout... but who knows... I also haven't looked at fastcgi or nginx config changes as I am assuming the wp-cron ignore_user_abort(true) setting would mean any termination of the connection from a fastcgi timeout or nginx setting would get ignored by the process anyway - but perhaps I'm wrong on that assumption

**Comment by thenbrent** [comment]
@rsouthgate all the search results for that error message are related to HHVM, so it's definitely related to that: https://cloudup.com/cQcbxUK4ecR

This tutorial was reporting the same error and has steps to resolve it: https://udinra.com/blog/hhvm-fastcgi-nginx-speedup-php

It sounds like you need to set `max_execution_time` in HHVM's `php.ini`.

FWIW, there are many setups where `set_time_limit()` has no effect. We use it in Action Scheduler because it's our only application level option to try to avoid script timeouts, but it's by no means guaranteed and large queues on special server setups (like yours) often require server level tweaks. 
Because of that, I'm closing this issue as its an issue with server configuration not the Action Scheduler code.

I hope the above information helps you resolve the issue. 🙂

**Comment by rsouthgate** [comment]
Hi,
I'm sure you're right this is hhvm config... can't for the life of me figure it out though. Tried many different configuration tweaks and while some hhvm processes would respect the set_time_limit as defined in my filter others would fail after 120 seconds so I'd end up with a mix of Fatal errors! like it's executing two different jit compiled codebases at random.

Anyway, in an effort to bypass that weirdness I changed the configuration so that cron would call wp cli directly:
```
wp cron event run --due-now
```
figuring at least this would bypass any fastcgi, nginx and even hhvm server timeouts.

These are fairly long running processes but the wp cron cli returns as soon as it's triggered the action_scheduler_run_queue, which doesn't seem to spawn any other processes (or wait before returning) so the scheduled actions end up as completed very quickly but the actual action only gets a tiny way along.

Don't suppose anyone knows what's going on here and any way I can tell the WP CLI tool to wait indefinitely for the action schedule?

**Comment by thenbrent** [comment]
> the scheduled actions end up as completed very quickly but the actual action only gets a tiny way along.

What is the code you have running on the scheduled action?

I'm not sure how WP CLI runs WP-Cron, but It's possible it is using a similar approach to that used when the `ALTERNATIVE_WP_CRON` is set, which has this known issue: https://core.trac.wordpress.org/ticket/24160

That could lead to the symptoms you're seeing, because WP-Cron may be run & existing with a priority on `'init'` later than `'wp_cron'`, which is `10`.
