### ISSUE TITLE
Unable to detect the Action Scheduler package

### ISSUE THREAD

**Issue by Naveed-Ahmad1** [Prospress/action-scheduler#811]
Hi,

I am getting this Error in WooCommerce > Status. Website Database size increasing day by day and reach almost 6500 MB. I have seen that it's woocommerce doing so. 

[https://ibb.co/k50DQLv](https://ibb.co/k50DQLv)

Please let me know to resolve this issue?

**Comment by jorgeatorres** [comment]
Hi @Naveed-Ahmad1!

Thanks for your report. Could you please share some more details about the issue you're having? For example, could you please copy & paste your System Status Report so that we can better understand what's going on. You can obtain it by going to WooCommerce > Status and clicking "Get system report".

Thanks again!
