### ISSUE TITLE
Delete hooks with wp cli

### ISSUE THREAD

**Issue by kevin25** [Prospress/action-scheduler#834]
Is there anyway to delete the schedule action with hooks? For example, i would like to delete the hook rank_math/analytics/ but there is no way to use wp cli. I have more than 20k

**Comment by barryhughes** [comment]
Hi @kevin25,

I'm just a little unsure if you mean you cannot currently access WP CLI, or if you *can* access it but don't see a way to accomplish your goals. The following would certainly be one possibility, if it is available to you:

```sh
wp eval "as_unschedule_all_actions( 'hook' );"
```

See [docs here](https://actionscheduler.org/api/#function-reference--as_unschedule_all_actions) for more info on that function. Otherwise, you would need to do the necessary work via the web UI, or perhaps via a SQL tool such as PhpMyAdmin or similar.

**Comment by crstauf** [comment]
@kevin25 Several PRs were submitted years ago that would have introduced that functionality, but the AS team is uninterested in WP CLI commands for some reason. 😞

I've been slowly developing a companion plugin, ~but it's not ready yet~. I'll try and get it out soon.

EDIT: Actually, it's looking okay. 🤷‍♂️ No promises of course, but you can check it out here:
https://github.com/crstauf/action-scheduler-cli/.

**Comment by bahiirwa** [comment]
Building something in relation as well. Thanks for the companion plugin. https://wordpress.org/plugins/cleanup-action-scheduler/

**Comment by barryhughes** [comment]
Thanks for sharing those links :-)

We have some provisional plans to introduce a dedicated WP CLI command to clean-up actions (plus other mitigations to keep table sizes in check), but will close this issue in the meantime.
