### ISSUE TITLE
Is it possible to lessen the interval time on as_enqueue_async_action for specific plugin use only(not global)

### ISSUE THREAD

**Issue by markgabinete** [Prospress/action-scheduler#842]
Is it possible to lessen the interval time on as_enqueue_async_action for specific plugin use only(not global)? I refer to the sleep time as of now I think it is set to 60sec.
Thank you

**Comment by jorgeatorres** [comment]
Hi @markgabinete,

Thanks for reaching out! There is currently no way to modify the lock which affects async actions, in a way that is specific to a given plugin.
The only way is to do it globally via the `action_scheduler_lock_duration` filter, but I believe you were already aware of this per your message above.

Could you please share a bit more context on use case is here? Maybe we can figure out a different way to achieve what you need.

Thanks!

**Comment by markgabinete** [comment]
Thank you for your time.
Yes we would love to share some details.
We have already integrated the action scheduler in our plugin which works really great now and we are just looking into the possibility of making the lock duration lesser maybe about 20-30 secs just for our plugin's async actions or just when are async function's batch is enqueued, to make the build time faster, without interrupting any other scheduled actions like from woocommerce and another plugin.

Thanks

**Comment by barryhughes** [comment]
Hi @markgabinete,

If the specific actions you want to run at a higher frequency belong to a single group, you could potentially invoke them via WP CLI (and you could do this from system cron or some other suitable tool, to invoke them at whatever frequency you desire):

`wp action-scheduler run --group=mygroup`

That way, only actions belonging to `mygroup` will be executed through this pathway. You could also increase the number of concurrent batches per [these instructions](https://actionscheduler.org/perf/) to make sure your 'regular' actions are not blocked in any way.

Might that help? The instructions I linked to may also be of general interest as you look into tuning performance.

**Comment by markgabinete** [comment]
Yes they belong to a single group, and we want them to run one at a time and it is already running one at a time by default, the only thing we are trying to change is the "action_scheduler_lock_duration" but not globally.

As mentioned above, we can do this in the WP CLI which would possibly involve creating a cron job for our action group and running at our desired schedule or time right?
 As we are working on a plugin, will there be a way for this to be achieved without the users setting up the cron jobs?

Thank you

**Comment by barryhughes** [comment]
I'd definitely refer you again to [these docs](https://actionscheduler.org/perf/) (regarding performance considerations) and also to the [High Volume plugin](https://github.com/woocommerce/action-scheduler-high-volume) if only to borrow implementation details.

> The only thing we are trying to change is the "action_scheduler_lock_duration" but not globally.

Understood. You can change the duration according to the type of lock (I think the lock you are interested in here is `async-request-runner`) but there is no method of reducing this in relation to a specific action or group of actions.

*However,* please specifically review the [Increasing Initialisation Rate of Runners](https://actionscheduler.org/perf/#increasing-initialisation-rate-of-runners) section of the docs. With reference to the snippet provided there and specifically example function `eg_create_additional_runners()`, you could probably make the additional queue runners target only your specific group.

**Comment by markgabinete** [comment]
We have reviewed and tried out your suggestions and it seems to work but I just have some more questions for confirmation.
Increasing Initialisation Rate of Runners -> As I have noticed when I have implemented it , it does run more frequently even if the lock is still counting. Which is good, is this the real purpose of this function? to initialize runners more frequently despite the lock duration?

Also I have some more questions
![image](https://user-images.githubusercontent.com/60727346/186592302-12e4891d-c09a-47c8-b64e-28f073a5bc40.png)

In the image, what does point 1 achieves? Am I correct in assuming that running additional loopback request up to 5 work along side the allowed concurrent batches?

I'm not sure about point 2 and 3, what happens if I change or customize them?
I have implemented this already looks great, but I had one issue I have encountered a max execution time, how can we prevent this as being a plugin it would be installed in different server configurations and capacity.
![image](https://user-images.githubusercontent.com/60727346/186592951-c3e67661-8b8a-44e7-a7a0-ac7a5b201502.png)

And lastly, 

How can we target the additional runners only to our specific group.

We greatly appreciate your assistance.

**Comment by barryhughes** [comment]
> Which is good, is this the real purpose of this function? to initialize runners more frequently despite the lock duration?

Not *quite.*

The goal of that function is to spawn an additional 5 queue runner requests for every one that Action Scheduler generates by default. By itself, it doesn't really know or care about the duration of the `async-request-runner` lock.

So—using this methodology and assuming you don't modify the lock duration (and that the [maximimum number of concurrent batches](increasing-concurrent-batches) is set to a suitable value such as `6`)—the result would *potentially* be 6 queue runners starting every minute.

That may or may not be useful in your specific case because, for example, if the first queue runner claims all of the waiting actions, then the remaining 5 queue runners will simply 'stand down'. I'm just highlighting that because the best configuraton for you is really going to depend on the sort of workloads you are dealing with, and the snippet I linked to is just one of a suite of ways you can better tailor things to meet your needs.

> In the image, what does point 1 achieves? Am I correct in assuming that running additional loopback request up to 5 work along side the allowed concurrent batches?

It creates those additional requests, yes. It doesn't circumvent the allowed concurrent batch check, however.

> I'm not sure about point 2 and 3, what happens if I change or customize them?

Those are HTTP request properties. Please see [this reference](https://developer.wordpress.org/reference/classes/WP_Http/request/) to learn more.

> I had one issue I have encountered a max execution time, how can we prevent this as being a plugin it would be installed in different server configurations and capacity.

You can use the filter hook `action_scheduler_queue_runner_time_limit` to specify a higher time limit or else you could attempt to [handle this directly](https://www.php.net/manual/en/function.set-time-limit.php) from within your callbacks. However, if your plugin is being deployed to servers over which you have limited control, be aware that there are no guarantees either approach will be successful.

> How can we target the additional runners only to our specific group.

This is a more advanced subject and will require some custom development. You would need to handle the claim process yourself, and specify the group you are interested in at that point. You may be interested in how the `wp action-scheduler run` CLI command (which supports specifying a specific group) handles this:

https://github.com/woocommerce/action-scheduler/blob/3.4.2/classes/WP_CLI/ActionScheduler_WPCLI_QueueRunner.php#L66

**Comment by markgabinete** [comment]
Thank you for your help, we appreciate the support.
