### ISSUE TITLE
3.4.X vs 3.5.X versions conflict

### ISSUE THREAD

**Issue by olegabr** [Prospress/action-scheduler#852]
This issue occured when the [Rank Math SEO](https://wordpress.org/plugins/seo-by-rank-math/) plugin updated their action-scheduler library used from 3.4.X to 3.5.X in the latest 1.0.97 version.
Everything works OK with the previous 1.0.96 [Rank Math SEO](https://wordpress.org/plugins/seo-by-rank-math/) plugin version, which uses the 3.4.X action-scheduler lib.

The code in the [Ethereum Wallet PRO](https://ethereumico.io/product/wordpress-ethereum-wallet-plugin/) plugin:

```php
$next_action = as_next_scheduled_action($hook, $args, $group);
if (false === $next_action) {
    $task_id = as_schedule_single_action($timestamp, $hook, $args, $group);
}

```

The [Ethereum Wallet PRO](https://ethereumico.io/product/wordpress-ethereum-wallet-plugin/) plugin uses the 3.4.2 action-scheduler library version. You do not need this plugin to reproduce this error, just install WooCommerce, [Rank Math SEO](https://wordpress.org/plugins/seo-by-rank-math/) and add the `as_schedule_single_action` call in functions.php for example.

```
Fatal error: Uncaught Error: Call to undefined method ActionScheduler_ActionFactory::single_unique()
in /var/www/html/wp-content/plugins/seo-by-rank-math/vendor/woocommerce/action-scheduler/functions.php on line 40

Call stack:

as_schedule_single_action()
wp-content/plugins/ethereum-wallet-premium/ethereum-wallet.php:665
ETHEREUM_WALLET_enqueue_adjust_balance_task()
wp-content/plugins/ethereum-wallet-premium/ethereum-wallet.php:722
ETHEREUM_WALLET_user_ping()
wp-includes/class-wp-hook.php:307
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:331
WP_Hook::do_action()
wp-includes/plugin.php:476
do_action()
wp-settings.php:620
require_once()
wp-config.php:95
require_once()
wp-load.php:50
require_once()
wp-admin/admin.php:34
```

**Comment by barryhughes** [comment]
Hi @olegabr,

I wanted to note first of all that there were some problems with recent releases of Action Scheduler, and specifically with the version resolution code that tries to ensure only one version of Action Scheduler is actually loaded (and that the loaded version should be the latest available version). Owing to those problems, we just released [3.5.2](https://github.com/woocommerce/action-scheduler/releases/tag/3.5.2) and patched the existing [3.5.1](https://github.com/woocommerce/action-scheduler/releases/tag/3.5.1) release.

However, I was unable to confirm if that was the same problem you are facing because, when running WooCommerce (which currently bundles [Action Scheduler 3.4.2](https://plugins.trac.wordpress.org/browser/woocommerce/tags/6.9.2/packages/action-scheduler/action-scheduler.php#L8)) alongside Rank Math SEO (which includes [Action Scheduler 3.5.1](https://plugins.trac.wordpress.org/browser/seo-by-rank-math/tags/1.0.97/vendor/woocommerce/action-scheduler/action-scheduler.php#L8)), it was the latter which loaded and there was no problem. Adding the snippet you shared to the active theme's `functions.php` file, or simply making it run during the `init` action, did not trigger the error you shared.

Is there anything else I would need in place to see the problem? The stack trace you shared makes me think that the `functions.php` file for 3.5.1 is being loaded, but that an autoloader is referencing the classes from 3.4.2. I'm still trying to put together why that might happen: if you have any thoughts that might help, they'd be appreciated.

**Comment by barryhughes** [comment]
Update:

- @olegabr shared a copy of Etherium Wallet Pro so I could test things out in more detail (thank you!).
- That plugin seems to include Action Scheduler classes (in this case, from 3.4.2) in its class-map.
- When running alongside other plugins shipping more recent versions of Action Scheduler (such as 3.5.2), this can lead to a conflict (since Etherium Wallet Pro's class-loader is loading classes from its own older copy of Action Scheduler, but the more recent version of Action Scheduler will already have loaded some of its own classes).

To avoid this sort of situation, the best strategy is to follow the usage instructions for [loading Action Scheduler](https://actionscheduler.org/usage/#loading-action-scheduler) and avoid including Action Scheduler in your Composer's autoloader rules.

**Comment by olegabr** [comment]
Thank you @barryhughes for a valuable support.

For those who want to have both, autoload classmap optimisation and workable action-scheduler in the same time, use it this way in your `composer.json` file:

```
  "autoload": {
    "classmap": [
      ""
    ],
    "exclude-from-classmap": [
      "/vendor/woocommerce/action-scheduler"
    ],
    "files": [
      "vendor/woocommerce/action-scheduler/action-scheduler.php"
    ]
  },

```
