### ISSUE TITLE
Scheduling an action fails quite bad when AS tables are missing

### ISSUE THREAD

**Issue by jorgeatorres** [Prospress/action-scheduler#856]
Related to https://github.com/woocommerce/woocommerce/issues/34497, when AS tables are missing, `as_schedule_recurring_action()` throws a fatal exception.
This could make it impossible to get to WooCommerce > Status > Action Scheduler, where the tables can be effectively regenerated.

This isn't incorrect in itself and WC could do a better job at capturing and handling these exceptions, but maybe AS could attempt to re-generate those tables "on the fly" or at least fail to report it has been fully initialized when scheduling an action will result in a fatal error.
This might be tricky due to the data-store-agnostic way things work, but maybe something we can explore in the future.

To reproduce:

1. Install WC.
2. Delete table `actionscheduler_actions`.
3. Site crashes.

**Comment by remyperona** [comment]
It might also be good to update the inline documentation for the API functions to indicate what kind of exceptions they can throw, so that 3rd party can guard against them.

Currently if you don't dig into the AS code, you have no idea that exceptions can be thrown by those functions.

**Comment by coreymckrill** [comment]
Idea: we could add a [Site Health Status](https://wordpress.org/documentation/article/site-health-screen/#status) check for the Action Scheduler tables, along with a tool for attempting to repair them.

**Comment by barryhughes** [comment]
> when AS tables are missing, as_schedule_recurring_action() throws a fatal exception.

I'm wondering if we should close this (cc @jorgeatorres for thoughts). Partly because, if the actions table is missing, `as_schedule_recurring_action()` no longer throws a fatal (it simply returns `(int) 0`) but also because we have a crop of other related issues that I think we can use to cover this sort of problem (they come at it from slightly different angles, but even so):

- https://github.com/woocommerce/action-scheduler/issues/1059
- https://github.com/woocommerce/action-scheduler/issues/973
- https://github.com/woocommerce/action-scheduler/issues/1032

Perhaps we can even consolidate some of the above.

**Comment by jorgeatorres** [comment]
@barryhughes: Makes sense. Feel free to close!
