### ISSUE TITLE
WooCommerce inbuilt action scheduler - over 5 million in pending

### ISSUE THREAD

**Issue by ESVPaul** [Prospress/action-scheduler#866]
I have an issue with Action Scheduler. It is showing over 5 million actions in the pending section. These all seem to be ced_ebay..... I have spoken with the plug in creater and they replyed with; "Hi @Paul Scott , our eBay plugin uses WooCommerce inbuilt action scheduler to process stock updates in the background for faster stock syncing to eBay. If the scheduled actions are not being run that means siteground is interfering with the WP Cron. Please get in touch with them and let them know about the issue. Thanks." 

What do I do? How can I mass delete all of these? 

Still learning but can give anything a go. 

![WhatsApp Image 2022-10-03 at 8 49 01 PM](https://user-images.githubusercontent.com/106995527/193761324-eb1ed840-da33-4ef6-b5d6-69720aaa8ebf.jpeg)

**Comment by peterfabian** [comment]
Hi @ESVPaul !

That's a lot of pending actions, and since the product IDs are different, my assumption is that those are valid stock-level updates for products in your shop. 

We'd suggest the following steps:
- check with the ebay plugin support if there are other ways to sync stock levels. If there are, you can delete the actions and the stock level updates will be propagated correctly. If not, you probably don't want to remove all those actions unless you don't care about stock level sync.
- You can delete the actions quickly e.g. by running a SQL query, probably best if it's provided by the ebay plugin authors as they know best which actions they schedule and what parameters to filter by  

- check with your hosting if WP Cron is running in your WP instance. Alternatively, you can run those actions more quickly using WP-cli, if you or your developer has access to that in your hosting environment. You can use command `wp action-scheduler run` to process all the actions more quickly, or if you want to process only a specific group, you can use e.g. `wp action-scheduler run --group='ced_ebay_inventory_scheduler'`.

Please note that having this many actions also means other scheduled actions in your shop might never actually be executed, so features like analytics, webhooks and other asynchronous processing will suffer.

Hope this helps,
Thanks!
