### ISSUE TITLE
Completed actions and associated logs stopped getting deleted - set TTL

### ISSUE THREAD

**Issue by ShedFlu** [Prospress/action-scheduler#880]
One of our customers WooCommerce databases has 10M+ records in actionscheduler_actions and 30M+ records in actionscheduler_logs, that startet to accumulate about 4 month ago.
I wasn't yet able to find the culprit, but I want to fix this for the time being.

Can i use a Filter or Hook to tell the action scheduler to delete completed actions after n days?

_I couldn't find any useful info on actionscheduler.org and in the issues about that but i may have overlooked sth._

**Comment by peterfabian** [comment]
Hi @ShedFlu , thanks for contacting us. 

Do you know if the accumulation happens because many actions are being scheduled in quick succession or if the cleanup fails somehow? Can you see any related errors in the PHP or SQL log perhaps?

Generally speaking, Action Scheduler should clean up 20 old actions each time a batch of actions runs. So if the customer's store creates actions more quickly, it can lead into problems. 

What might be happening is that the query to get the actions to delete times out and nothing gets cleaned up.

You can use the following filters to fine-tune the action clean up:
- `action_scheduler_cleanup_batch_size`: how many actions to clean up per processed batch; default value is 20
- `action_scheduler_retention_period`: for how long the completed/cancelled actions are kept (number of seconds); default is one month

Additionally, you can try to activate the WP CLI runner (`action-scheduler run`) which might give you more RAM and resources than the web server. You can find more docs over here: https://actionscheduler.org/wp-cli/


As for the logs table, I believe it should be fine to TRUNCATE it using SQL, unless your customer needs the data about past actions.

If you need to act manually on the actions table, then you should be safe deleting all the rows with `complete` and `canceled` status that haven't been updated in the past week/month.

Hope this helps!

**Comment by ShedFlu** [comment]
Hello @peterfabian ,
thanks for the fast reply!

20 cleared rows per run should have been enough, but it looks like the size of the cleanup batch was too small compared to the amount of updates scheduled every minute.
Setting the action_scheduler_cleanup_batch_size to a higher value helped, but it didn't feel quite right.

So we kept looking and found [this quote](https://wordpress.org/support/topic/very-large-amount-of-scheduled-actions/) from WP All Import Support:
> Unfortunately, this is a feature of WooCommerce that was added recently and is not supposed to be turned off (part of the gradual move to custom database tables). But if you change your settings to update immediately instead of being scheduled to update, that may help (in the WooCommerce settings)

Can be found under _WooCommerce Settings -> Products -> Advanced -> Direct Updates_

This solution also works, but we're not sure which one is better, since updates are likely deferred by default for a reason.
Can you think of any problems that could be caused by this fix in the long term?

**Comment by barryhughes** [comment]
Hi @ShedFlu,

> Setting the action_scheduler_cleanup_batch_size to a higher value helped, but it didn't feel quite right.

Different sites have different workloads, and the default settings for things like clean-up batch size aren't necessarily a one-size-fits-all. 

It's fine to adjust this, and test different values until you find a fit that works for you. So long as scheduled actions continue to be processed successfully, and you don't see other adverse affects—if you do, simply roll back the change—this is a very reasonable approach.

> This solution also works, but we're not sure which one is better

Neither is inherently better, they simply offer different trade-offs. If it is important to reflect changes to product attributes almost immediately on the frontend, this setting makes the most sense. Again it's something where you can enable the setting, monitor the impact, and roll-back if needed.

**Comment by barryhughes** [comment]
Internal discussion p7bje6-4ph-p2 also relates. Closing, though, since it sounds like further support is not needed at this time (but do let us know if I'm mistaken on that count).
