### ISSUE TITLE
A lot of pending tasks due to the async tasks from wp-rocket

### ISSUE THREAD

**Issue by januzi** [Prospress/action-scheduler#895]
Hello
I've noticed that the tasks from woocommerce aren't being executed. I've spent some time looking at the in-progress tab and at the pending list. The first 4 or 5 pages in the pending list are filled with the tasks from the wp-rocket, that's preloading the content. As soon as the rocket-preload tasks are being finished, the new ones are being added to the list. 

It looks for me that action scheduler is prioritizing tasks that are set as "async", and since wp-rocket is adding new tasks constantly, there's no way that the regular tasks will be even picked up for the execution. I've found a plugin that multiplied the size of the batch, made more concurent batches and executed more runners. It helped a little, but then the server started to show a lot of 504 errors, so that plugin clearly isn't the right solution in my case. 

Is there a way to force scheduler to pick the tasks that have the scheduled time in the past, and if there's none, then focus on the async tasks?

**Comment by barryhughes** [comment]
Hi @januzi,

I agree the current situation is not ideal.

> Is there a way to force scheduler to pick the tasks that have the scheduled time in the past, and if there's none, then focus on the async tasks?

Older tasks are prioritized over newer tasks, but the reason this breaks down in the case of async tasks is that they are scheduled for `0000-00-00 00:00:00` ... and therefore always *look* older than truly aged actions. Possibly, we could/should change things so that async means 'now' (current date/time) instead of year zero.

In terms of what you can do about this problem in the short-term, something like the following snippet might help (you could for instance place this inside a file such as `wp-content/mu-plugins/action-scheduler-tweaks.php`):

```php
/**
 * Attempts to stop async actions from being given priority over over-due single/recurring actions.
 */
add_filter( 'action_scheduler_claim_actions_order_by', function () {
	$now = date_create( 'now', timezone_open( 'UTC' ) )->format( 'Y-m-d H:i:s' );
	$scheduled_date_order = "CASE scheduled_date_gmt WHEN '0000-00-00 00:00:00' THEN '$now' ELSE scheduled_date_gmt END ASC";
	return "ORDER BY attempts ASC, $scheduled_date_order, action_id ASC";
} );
```

The idea is that when a set of actions are claimed—which happens immediately before they are processed—we treat the async actions as being due 'now' and therefore this does not prevent single actions that are *past due* from also being claimed.

However, this is of course just a temporary shim you can test and use as an interim measure. I think what we really need to do is make a change in the library itself (we can then do the same thing, but in a more performant manner) and so I'll go ahead and mark this as a future enhancement.

Thanks!
