### ISSUE TITLE
Action scheduler needs to clean up trashed posts

### ISSUE THREAD

**Issue by JPry** [Prospress/action-scheduler#90]
Related to the work I was doing on Prospress/woocommerce-subscriptions#2246, I noticed that posts with a type of `scheduled-action` are not deleted when their parent order is deleted. They ***are*** marked correctly as trashed. I don't know if these will be cleaned up by the action scheduler or if some code adjustments need to be made.

![2017-08-23_1036](https://user-images.githubusercontent.com/871924/29621517-f4a53ab2-87ee-11e7-9400-6ff532817230.png)

**Comment by thenbrent** [comment]
The actions will be auto-deleted by WP. Because a scheduled action can have any data as its args, not just a post and certainly not just a subscription post type, we can't generically delete the data in Action Scheduler when a corresponding object is delete.

It's certainly something we could do in Subscriptions in `WCS_Action_Scheduler`, but for now, I'd like to focus on energies on [migrating AS to custom tables](https://github.com/prospress/action-scheduler-custom-tables/) and making that great, as it's the more important thing. So I'm going to close this. It would have been great to discover a few years ago! haha
