### ISSUE TITLE
Notify when task fails and retries are exhausted

### ISSUE THREAD

**Issue by amp42** [Prospress/action-scheduler#908]
I am a user of a plugin that implements a data exchange/sync between WP and an external service. The plugin polls the external service and when it detects a worthy event, it pulls the data from external service over to WP. The plugin uses AS to implement polling and data retrieval by scheduling a series of AS tasks. The recurrence is via WP Cron. 

Occasionally, an AS task generated by the plugin fails to contact the external service. After the task is retried and the max number of retries is reached, the plugin logs this error from AS:

```This action appears to be consistently failing. A new instance will not be scheduled.```

We'd like to be notified when the AS task fails and the retries are exhausted. My attempt:

```php
add_action('action_scheduler_failed_execution', my_failed_action_handler_v1, 10, 3);
add_action('action_scheduler_failed_execution', my_failed_action_handler_v2, 10, 3);

function my_failed_action_handler_v2(const string $action_id, $ex, $context) {
		$action = ActionScheduler::store()->fetch_action($action_id);
		if (
			ActionScheduler_Store::STATUS_FAILED === ActionScheduler::store()->get_status( $action_id )
			&& ActionScheduler::store()->recurring_action_is_consistently_failing( $action, $action_id )
		) 
		{
			 wp_mail(...);
		}
}

function my_failed_action_handler_v1(const string $action_id, $ex, $context ) {
	
    $error_message = $ex->get_error_message();
    if ( strpos( $error_message, 'new instance will not be scheduled' ) !== false ) {
        wp_mail( ... );
    }
}
```

My questions:

1. Is `action_scheduler_failed_execution` the right hook

2. If possible, I would prefer not to rely on string matches (the v1 handler). Is the condition in v2 correct in terms of catching the dead task? I based it on [QueueRunner](https://github.com/woocommerce/action-scheduler/blob/trunk/classes/abstracts/ActionScheduler_Abstract_QueueRunner.php)

I did read the docs and AS source code but I might have missed something. Pointers to docs and/or examples are welcome.

**Comment by barryhughes** [comment]
Hi @amp42,

> We'd like to be notified when the AS task fails and the retries are exhausted ... is `action_scheduler_failed_execution` the right hook?

It's the closest hook we have available at present. It fires if the action fails, but that doesn't necessarily mean that retry attempts are exhausted (and, looking at your code, it is pretty clear that you realize this, but I wanted to spell it out for the benefit of others coming across this issue).

> If possible, I would prefer not to rely on string matches (the v1 handler). Is the condition in v2 correct in terms of catching the dead task? I based it on [QueueRunner](https://github.com/woocommerce/action-scheduler/blob/trunk/classes/abstracts/ActionScheduler_Abstract_QueueRunner.php)

It's definitely on the right track, but method `recurring_action_is_consistently_failing` is private and so cannot be called from external code (at least, not without some hacking). As a short term fix, an alternative would be to basically duplicate the code you see inside that private method.

Longer term, I think we would be open to changing Action Scheduler a little so that, in addition to logging a warning *('This action appears to be consistently failing...'),* we also trigger an action. That would allow you to do something like this:

```php
add_action( 'action_scheduler_failing_recurring_action', function ( $action_id, $hook ) {
    // Do something.
} );
```

Does that look like it would meet your needs?

**Comment by amp42** [comment]
@barryhughes Yes,  `action_scheduler_failing_recurring_action` or equivalent would meet my needs, thank you.
