### ISSUE TITLE
PHP 8 Failing DateTime

### ISSUE THREAD

**Issue by bahiirwa** [Prospress/action-scheduler#917]
Thanks for the work on this.

I am running PHP 8 
AS Plugin: 3.5.4 version

I am getting the Failing DateTime. The issue seems to be with `/www/com_643/public/wp-content/plugins/action-scheduler/functions.php(421): DateTime->__construct(' seconds ago', `. We might need to have the time as an integer.
or somethig else.

```
2023/02/27 17:46:34 [error] 52135#52135: *17723 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Exception: DateTime::__construct(): Failed to parse time string ( seconds ago) at position 0 (s): The timezone could not be found in the database in /www/com_643/public/wp-content/plugins/action-scheduler/functions.php:421
Stack trace:
#0 /www/com_643/public/wp-content/plugins/action-scheduler/functions.php(421): DateTime->__construct(' seconds ago', Object(DateTimeZone))
#1 /www/com_643/public/wp-content/plugins/action-scheduler/classes/ActionScheduler_QueueCleaner.php(34): as_get_datetime_object(' seconds ago')
#2 /www/com_643/public/wp-content/plugins/action-scheduler/classes/ActionScheduler_QueueCleaner.php(139): ActionScheduler_QueueCleaner->delete_old_actions()
#3 /www/com_643/public/wp-content/plugins/action-scheduler/classes/abstracts/ActionScheduler_Abstract_QueueRunner.php(160): ActionScheduler_QueueCleaner->clean(300)
```

**Comment by barryhughes** [comment]
Hi @bahiirwa,

By default, Action Scheduler will try to specify a period of `'2678400 seconds ago'` (broadly speaking, that means 'one month ago'). However, the precise period is configurable:

- Custom code snippets can use the `action_scheduler_retention_period` filter hook to change the period to some other value.
- Third party plugins and themes can also utilize the same hook.

Could that be the case here (ie, the problem is the result of custom code you added—or else some other plugin)? Either way we should probably be a bit more defensive in this area and look out for invalid values, so I'll mark this as a bug—but I suspect it is not a bug that impacts most users.

**Comment by bahiirwa** [comment]
In my case I guess is because I am using `as_enqueue_async_action()`. That is where the failures drop in.

![Screenshot 2023-02-28 at 20 39 49](https://user-images.githubusercontent.com/7713923/221933683-be3482e2-c99f-490e-9dc3-4548ae139ad0.png)

**Comment by barryhughes** [comment]
I could be missing something, but I don't believe the retention period automatically changes in that way. An expired action is an expired action, even if it was initially created using `as_enqueue_async_action()`—and the *default* retention period when performing clean-up will be 2,678,400 seconds regardless.

**Comment by bahiirwa** [comment]
I tried to clear my server and deleted all the queues and the error no longer show up.
Thanks for looking into this.

**Comment by barryhughes** [comment]
You're welcome. Re-opening it, though, because even if this is irregular, and doesn't happen by default, we can probably guard against the fatal error.
