### ISSUE TITLE
Pending Scheduled Actions are being increased over time

### ISSUE THREAD

**Issue by usman661** [Prospress/action-scheduler#949]
Hi, I see hundreds of thousands pending scheduled actions in WooCommerce Status and those are being increased over time. To be exact at this moment, there are 232335 pending scheduled actions. 

My store is synced with eBay. The products that I did zero inventory on eBay should reflect 0 on WooCommerce but it does not and instead increases the inventory on eBay. (I think this happens when a certain pending scheduled action is completed). Please help out how to kill those actions or get the completed asap.

Thank you

https://mosaicmachines.com/
![WooCommerce Pending Scheduled Actions](https://user-images.githubusercontent.com/64188565/236677659-6dda829f-7cc2-4bae-a7d2-f7068917770c.JPG)

**Comment by jorgeatorres** [comment]
Hi @usman661,

Thanks for reaching out and we're sorry that you're having trouble. You've said that some actions do complete, so this doesn't look like an issue with Action Scheduler itself, but the WooCommerce update routine that is probably not completing.
This could be due to a bug in 7.2.1 that was subsequently fixed in 7.2.2, but I can see from your screenshot that those actions are still pending execution (even though they will never really complete).

Our suggestion would be to manually remove those from the database. That is, delete all rows from the database table `actionscheduler_actions` where hook is `woocommerce_run_update_callback`. You'll have to be careful to only delete those or you'll wipe out all scheduled actions. We obviously suggest backing up the database before doing anything. You might consider reaching out to your host if you're not comfortable doing this.

As for the eBay sync, we can't really speak to that as we don't know how that works or if it uses Action Scheduler or not, but from the Action Scheduler side, a good first step would be to fix the database as we've described.
