### ISSUE TITLE
How to reschedule an async_action when it fails?

### ISSUE THREAD

**Issue by markgabinete** [Prospress/action-scheduler#953]
How to reschedule an async_action when it fails?
We implemented as_enqueue_async_action, but in some cases, it fails due to memory exhaust or max execution time.
How can we reschedule that async action when it fails?

Thank you

**Comment by barryhughes** [comment]
Hi @markgabinete,

If an action starts to run, but the process is terminated because max execution time has been reached, then the action will generally remain in a `pending` state (and will still be part of a claimed batch of actions). Action Scheduler regularly checks for this, and resets any such actions so they can be processed again. 

On the other hand, if you mean that the action is ending up with a `failed` status, that suggests a different sort of error condition. Some ideas:

- You can watch for this sort of failure by using the `action_scheduler_failed_execution` action hook, and then schedule a replacement action if needed.
- Or, depending on your use-case, you could have a recurring action that continually checks to see if a body of work is incomplete and schedules new async actions if so.

Does that help?

**Comment by markgabinete** [comment]
Ok thank you we will check this and let you know.
In our case, we would need to watch the failure with action_scheduler_failed_execution action hook and reschedule the failed action. Does this mean we can schedule a replacement action using the $action_id provided by this hook right?

Thank you for your help

**Comment by barryhughes** [comment]
> Does this mean we can schedule a replacement action using the $action_id provided by this hook right?

You could for example use the action ID to check if the failed action is one you are interested in, then reschedule from there:

```php
if ( ActionScheduler::store()->fetch_action( $action_id )->get_hook() === 'my_hook' ) {
	// Schedule replacement.
}
```
