### ISSUE TITLE
PHP Warning: `Warning: Undefined property: stdClass::$priority in [...]/libraries/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php on line 379`

### ISSUE THREAD

**Issue by strarsis** [Prospress/action-scheduler#958]
PHP 8 reports a PHP warning with current `action-scheduler`:
````
Warning: Undefined property: stdClass::$priority in [...]/libraries/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php on line 379
````

**Comment by barryhughes** [comment]
Hi @strarsis,

It's possible this is happening because your database structure was not updated during the most recent Action Scheduler update. To verify this, would you be comfortable running the following query?

```sql
-- Update the table prefix ("wp_") as needed.
DESCRIBE wp_actionscheduler_actions
```

You should see several rows in the response. Is this one ("priority") among them?

| Field | Type | Null | Default | 
| --- | --- | --- | --- |
| priority | tinyint unsigned | NO | 10 |

If the `priority` field is not present, and if you have access to WP CLI, you might try running the following command to fix things:

```sh
wp action-scheduler fix-schema
```

**Comment by gencmedya** [comment]
run the below query, please take a backup before running.
```
ALTER TABLE `wp_actionscheduler_actions` ADD `priority` TINYINT(3) UNSIGNED NOT NULL DEFAULT '10' AFTER `extended_args`;
```

**Comment by barryhughes** [comment]
- Closing in favor of https://github.com/woocommerce/action-scheduler/issues/973
- Both reports cover essentially the same problem. Though this is the older of the two, there are other gives a better sense of impact.
