### ISSUE TITLE
Actions marked as unique are scheduled twice

### ISSUE THREAD

**Issue by abaicus** [Prospress/action-scheduler#963]
Hello!

I have an issue with unique jobs. They get scheduled twice, even though they are marked as unique when `as_schedule_cron_action` is called:

```php
as_schedule_cron_action( time(), '15 * * * *', 'hourly_job', array( 'value_to_pass' => $args ), 'custom_group', true );
``` 

Here are a few more details:
- the call above runs on the `init` hook, with a priority of `2`;
- we have a similar action that mostly does the same thing and is added to the same group but runs daily (`0 5 * * * *`). This one doesn't get scheduled twice;
- I couldn't find any flag for the job in the DB that marks it as unique - at least in the `actionscheduler_actions` table - reading through the code, it seems that when scheduling a unique action, action-scheduler does a query to search that no other similar action is scheduled;
- looking at the logs table, it seems that the actions are created at the same time: 
![image](https://github.com/woocommerce/action-scheduler/assets/15010186/50c6299a-a522-40c2-8ca8-480bf691b3a8)
- we have Redis object cache enabled. I'm not sure if that could impact this in any way;

Do you have any insights on this? 

I appreciate any help you can provide! Thanks!

**Comment by Konamiman** [comment]
Hi @abaicus. We'd need a couple of pieces of information about your environment:

1. Which version of Action Scheduler are you using? Unique actions are supported since version 3.5.
2. Which actions store is configured? Unique actions are supported only for dbstore. You can check for that by running this command: `wp eval "echo apply_filters( 'action_scheduler_store_class', '' );"` (it should return `ActionScheduler_DBStore`).

If both your AS version and your actions store are fine, we'll label this as a bug and further investigate about it. Thank you!

**Comment by abaicus** [comment]
Hi @Konamiman. Thank you for the prompt answer!

1. Version 3.6.0;
2. The command returns `ActionScheduler_DBStore` indeed;

Thank you!

**Comment by barryhughes** [comment]
Thanks!

I tried replicating on a new/clean testing site—with the latest version of Action Scheduler, a persistent object cache, and the following snippet:

```php
add_action( 'init', function () {
	as_schedule_cron_action( time(), '15 * * * *', 'hourly_job', array( 'value_to_pass' => 'foo' ), 'custom_group', true );
}, 2 );
```

I did not notice the creation of duplicates.

- If you try this out on your end (again, on a clean site where no other plugins are running), do you find the same?
- Or, can you expand the snippet so we have a minimal amount of code that lets us replicate?
- Can you test with Redis disabled? Depending on the caching plugin you are using, this may be as easy as adding `define( 'WP_REDIS_DISABLED', true );` to your *wp-config.php* file (but, check with that plugin's support team first).

Thanks!

**Comment by abaicus** [comment]
Hello, @barryhughes! 

Thank you for your reply! 

We have a similar environment for the staging website - with much less traffic and Redis disabled, and this doesn't happen there. 

This may be happening due to the high traffic and racing conditions, as the uniqueness of the scheduled actions is checked via PHP instead of MYSQL.

**Comment by barryhughes** [comment]
So the idea behind unique actions is to rely on a single MySQL query, rather than on checks performed in the application code:

[`ActionScheduler_DBStore::build_where_clause_for_insert()`](https://github.com/woocommerce/action-scheduler/blob/3.6.1/classes/data-stores/ActionScheduler_DBStore.php#L171-L203)

However, perhaps there are conditions where this is circumvented or compromised in some way. Can you provide some more detail on where you see unique actions relying on PHP code?

**Comment by barryhughes** [comment]
Hi @abaicus—just checking back in, in case there are any other notes you can share on this one (and in case we missed something with the unique action implementation).

**Comment by abaicus** [comment]
Hey @barryhughes,

 I'm sorry for the late reply!

In the end, this was an env issue. We've since moved all the scheduling to happen only in the WP_CLI context - we have a command running every minute through AWS Eventbridge that will also schedule the actions. 

Our env is set up with [ymir](https://ymirapp.com/) and is quite heavy on traffic. I think some things ran concurrently when scheduling the actions, coupled with caching. 

Thank you for your help!

**Comment by barryhughes** [comment]
Perfect, thanks for confirming. I'll close this issue, but if anything else crops up feel free to post fresh ones.
