### ISSUE TITLE
action_scheduler/migration_hook Running Every Minute or Less | Also Stuck in Pending

### ISSUE THREAD

**Issue by puppacito** [Prospress/action-scheduler#979]
I've had woocommerce for a few years now and have updated it continuously, so I'm not sure how old this issue is. I recently cleared the log of over 24,000 instances of this, so I have to assume its been going on for a little while now. I have two actions stuck in pending that are also running in a perpetual loop. Here's the screenshots I am seeing, as well as the database. Any help is greatly appreciated

![Screenshot 2023-09-01 224646](https://github.com/woocommerce/action-scheduler/assets/87211619/82575338-de44-43e4-a2b6-865547945a0f)
![Screenshot 2023-09-01 224704](https://github.com/woocommerce/action-scheduler/assets/87211619/e4f734b2-84c3-4ed0-a5b7-a3e9d75dd346)
![Screenshot 2023-09-02 112010](https://github.com/woocommerce/action-scheduler/assets/87211619/10866a8a-b30e-4cf1-969d-e99f07bbf254)

**Comment by coreymckrill** [comment]
@puppacito This is a weird old issue that we've never been able to replicate consistently. A couple of things to check on:

* Since you can poke around in the database with phpMyAdmin, do you have any posts in the posts table that are of the type `scheduled-action`?
* If you go to WooCommerce > Settings > Status > Logs, are there any error logs related to Action Scheduler?

**Comment by coreymckrill** [comment]
If there aren't any `scheduled-action` posts, and you have access to [WP CLI](https://wp-cli.org/) on your site, you could run this command to make it stop:

`wp option update action_scheduler_migration_status complete`

**Comment by lsinger** [comment]
We'll close this issue for now in lieu of #990. If there's more to this that's not covered there, please feel free to reopen this discussion or open a new issue.
